// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// DeleteReposOwnerRepoContentsPathOKCode is the HTTP code returned for type DeleteReposOwnerRepoContentsPathOK
const DeleteReposOwnerRepoContentsPathOKCode int = 200

/*DeleteReposOwnerRepoContentsPathOK OK

swagger:response deleteReposOwnerRepoContentsPathOK
*/
type DeleteReposOwnerRepoContentsPathOK struct {

	/*
	  In: Body
	*/
	Payload *models.DeleteFile `json:"body,omitempty"`
}

// NewDeleteReposOwnerRepoContentsPathOK creates DeleteReposOwnerRepoContentsPathOK with default headers values
func NewDeleteReposOwnerRepoContentsPathOK() *DeleteReposOwnerRepoContentsPathOK {
	return &DeleteReposOwnerRepoContentsPathOK{}
}

// WithPayload adds the payload to the delete repos owner repo contents path o k response
func (o *DeleteReposOwnerRepoContentsPathOK) WithPayload(payload *models.DeleteFile) *DeleteReposOwnerRepoContentsPathOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete repos owner repo contents path o k response
func (o *DeleteReposOwnerRepoContentsPathOK) SetPayload(payload *models.DeleteFile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteReposOwnerRepoContentsPathOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteReposOwnerRepoContentsPathForbiddenCode is the HTTP code returned for type DeleteReposOwnerRepoContentsPathForbidden
const DeleteReposOwnerRepoContentsPathForbiddenCode int = 403

/*DeleteReposOwnerRepoContentsPathForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response deleteReposOwnerRepoContentsPathForbidden
*/
type DeleteReposOwnerRepoContentsPathForbidden struct {
}

// NewDeleteReposOwnerRepoContentsPathForbidden creates DeleteReposOwnerRepoContentsPathForbidden with default headers values
func NewDeleteReposOwnerRepoContentsPathForbidden() *DeleteReposOwnerRepoContentsPathForbidden {
	return &DeleteReposOwnerRepoContentsPathForbidden{}
}

// WriteResponse to the client
func (o *DeleteReposOwnerRepoContentsPathForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
