// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteReposOwnerRepoDownloadsDownloadIDHandlerFunc turns a function with the right signature into a delete repos owner repo downloads download ID handler
type DeleteReposOwnerRepoDownloadsDownloadIDHandlerFunc func(DeleteReposOwnerRepoDownloadsDownloadIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteReposOwnerRepoDownloadsDownloadIDHandlerFunc) Handle(params DeleteReposOwnerRepoDownloadsDownloadIDParams) middleware.Responder {
	return fn(params)
}

// DeleteReposOwnerRepoDownloadsDownloadIDHandler interface for that can handle valid delete repos owner repo downloads download ID params
type DeleteReposOwnerRepoDownloadsDownloadIDHandler interface {
	Handle(DeleteReposOwnerRepoDownloadsDownloadIDParams) middleware.Responder
}

// NewDeleteReposOwnerRepoDownloadsDownloadID creates a new http.Handler for the delete repos owner repo downloads download ID operation
func NewDeleteReposOwnerRepoDownloadsDownloadID(ctx *middleware.Context, handler DeleteReposOwnerRepoDownloadsDownloadIDHandler) *DeleteReposOwnerRepoDownloadsDownloadID {
	return &DeleteReposOwnerRepoDownloadsDownloadID{Context: ctx, Handler: handler}
}

/*DeleteReposOwnerRepoDownloadsDownloadID swagger:route DELETE /repos/{owner}/{repo}/downloads/{downloadId} deleteReposOwnerRepoDownloadsDownloadId

Deprecated. Delete a download.

*/
type DeleteReposOwnerRepoDownloadsDownloadID struct {
	Context *middleware.Context
	Handler DeleteReposOwnerRepoDownloadsDownloadIDHandler
}

func (o *DeleteReposOwnerRepoDownloadsDownloadID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteReposOwnerRepoDownloadsDownloadIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
