// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteReposOwnerRepoMilestonesNumberNoContentCode is the HTTP code returned for type DeleteReposOwnerRepoMilestonesNumberNoContent
const DeleteReposOwnerRepoMilestonesNumberNoContentCode int = 204

/*DeleteReposOwnerRepoMilestonesNumberNoContent No content.


swagger:response deleteReposOwnerRepoMilestonesNumberNoContent
*/
type DeleteReposOwnerRepoMilestonesNumberNoContent struct {
}

// NewDeleteReposOwnerRepoMilestonesNumberNoContent creates DeleteReposOwnerRepoMilestonesNumberNoContent with default headers values
func NewDeleteReposOwnerRepoMilestonesNumberNoContent() *DeleteReposOwnerRepoMilestonesNumberNoContent {
	return &DeleteReposOwnerRepoMilestonesNumberNoContent{}
}

// WriteResponse to the client
func (o *DeleteReposOwnerRepoMilestonesNumberNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteReposOwnerRepoMilestonesNumberForbiddenCode is the HTTP code returned for type DeleteReposOwnerRepoMilestonesNumberForbidden
const DeleteReposOwnerRepoMilestonesNumberForbiddenCode int = 403

/*DeleteReposOwnerRepoMilestonesNumberForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response deleteReposOwnerRepoMilestonesNumberForbidden
*/
type DeleteReposOwnerRepoMilestonesNumberForbidden struct {
}

// NewDeleteReposOwnerRepoMilestonesNumberForbidden creates DeleteReposOwnerRepoMilestonesNumberForbidden with default headers values
func NewDeleteReposOwnerRepoMilestonesNumberForbidden() *DeleteReposOwnerRepoMilestonesNumberForbidden {
	return &DeleteReposOwnerRepoMilestonesNumberForbidden{}
}

// WriteResponse to the client
func (o *DeleteReposOwnerRepoMilestonesNumberForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
