// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteReposOwnerRepoKeysKeyIDNoContentCode is the HTTP code returned for type DeleteReposOwnerRepoKeysKeyIDNoContent
const DeleteReposOwnerRepoKeysKeyIDNoContentCode int = 204

/*DeleteReposOwnerRepoKeysKeyIDNoContent No content.


swagger:response deleteReposOwnerRepoKeysKeyIdNoContent
*/
type DeleteReposOwnerRepoKeysKeyIDNoContent struct {
}

// NewDeleteReposOwnerRepoKeysKeyIDNoContent creates DeleteReposOwnerRepoKeysKeyIDNoContent with default headers values
func NewDeleteReposOwnerRepoKeysKeyIDNoContent() *DeleteReposOwnerRepoKeysKeyIDNoContent {
	return &DeleteReposOwnerRepoKeysKeyIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteReposOwnerRepoKeysKeyIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteReposOwnerRepoKeysKeyIDForbiddenCode is the HTTP code returned for type DeleteReposOwnerRepoKeysKeyIDForbidden
const DeleteReposOwnerRepoKeysKeyIDForbiddenCode int = 403

/*DeleteReposOwnerRepoKeysKeyIDForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response deleteReposOwnerRepoKeysKeyIdForbidden
*/
type DeleteReposOwnerRepoKeysKeyIDForbidden struct {
}

// NewDeleteReposOwnerRepoKeysKeyIDForbidden creates DeleteReposOwnerRepoKeysKeyIDForbidden with default headers values
func NewDeleteReposOwnerRepoKeysKeyIDForbidden() *DeleteReposOwnerRepoKeysKeyIDForbidden {
	return &DeleteReposOwnerRepoKeysKeyIDForbidden{}
}

// WriteResponse to the client
func (o *DeleteReposOwnerRepoKeysKeyIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
