// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteReposOwnerRepoIssuesCommentsCommentIDNoContentCode is the HTTP code returned for type DeleteReposOwnerRepoIssuesCommentsCommentIDNoContent
const DeleteReposOwnerRepoIssuesCommentsCommentIDNoContentCode int = 204

/*DeleteReposOwnerRepoIssuesCommentsCommentIDNoContent No content.


swagger:response deleteReposOwnerRepoIssuesCommentsCommentIdNoContent
*/
type DeleteReposOwnerRepoIssuesCommentsCommentIDNoContent struct {
}

// NewDeleteReposOwnerRepoIssuesCommentsCommentIDNoContent creates DeleteReposOwnerRepoIssuesCommentsCommentIDNoContent with default headers values
func NewDeleteReposOwnerRepoIssuesCommentsCommentIDNoContent() *DeleteReposOwnerRepoIssuesCommentsCommentIDNoContent {
	return &DeleteReposOwnerRepoIssuesCommentsCommentIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteReposOwnerRepoIssuesCommentsCommentIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteReposOwnerRepoIssuesCommentsCommentIDForbiddenCode is the HTTP code returned for type DeleteReposOwnerRepoIssuesCommentsCommentIDForbidden
const DeleteReposOwnerRepoIssuesCommentsCommentIDForbiddenCode int = 403

/*DeleteReposOwnerRepoIssuesCommentsCommentIDForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response deleteReposOwnerRepoIssuesCommentsCommentIdForbidden
*/
type DeleteReposOwnerRepoIssuesCommentsCommentIDForbidden struct {
}

// NewDeleteReposOwnerRepoIssuesCommentsCommentIDForbidden creates DeleteReposOwnerRepoIssuesCommentsCommentIDForbidden with default headers values
func NewDeleteReposOwnerRepoIssuesCommentsCommentIDForbidden() *DeleteReposOwnerRepoIssuesCommentsCommentIDForbidden {
	return &DeleteReposOwnerRepoIssuesCommentsCommentIDForbidden{}
}

// WriteResponse to the client
func (o *DeleteReposOwnerRepoIssuesCommentsCommentIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
