// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteGistsIDCommentsCommentIDNoContentCode is the HTTP code returned for type DeleteGistsIDCommentsCommentIDNoContent
const DeleteGistsIDCommentsCommentIDNoContentCode int = 204

/*DeleteGistsIDCommentsCommentIDNoContent No content.


swagger:response deleteGistsIdCommentsCommentIdNoContent
*/
type DeleteGistsIDCommentsCommentIDNoContent struct {
}

// NewDeleteGistsIDCommentsCommentIDNoContent creates DeleteGistsIDCommentsCommentIDNoContent with default headers values
func NewDeleteGistsIDCommentsCommentIDNoContent() *DeleteGistsIDCommentsCommentIDNoContent {
	return &DeleteGistsIDCommentsCommentIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteGistsIDCommentsCommentIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteGistsIDCommentsCommentIDForbiddenCode is the HTTP code returned for type DeleteGistsIDCommentsCommentIDForbidden
const DeleteGistsIDCommentsCommentIDForbiddenCode int = 403

/*DeleteGistsIDCommentsCommentIDForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response deleteGistsIdCommentsCommentIdForbidden
*/
type DeleteGistsIDCommentsCommentIDForbidden struct {
}

// NewDeleteGistsIDCommentsCommentIDForbidden creates DeleteGistsIDCommentsCommentIDForbidden with default headers values
func NewDeleteGistsIDCommentsCommentIDForbidden() *DeleteGistsIDCommentsCommentIDForbidden {
	return &DeleteGistsIDCommentsCommentIDForbidden{}
}

// WriteResponse to the client
func (o *DeleteGistsIDCommentsCommentIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
