// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteReposOwnerRepoDownloadsDownloadIDNoContentCode is the HTTP code returned for type DeleteReposOwnerRepoDownloadsDownloadIDNoContent
const DeleteReposOwnerRepoDownloadsDownloadIDNoContentCode int = 204

/*DeleteReposOwnerRepoDownloadsDownloadIDNoContent No content.


swagger:response deleteReposOwnerRepoDownloadsDownloadIdNoContent
*/
type DeleteReposOwnerRepoDownloadsDownloadIDNoContent struct {
}

// NewDeleteReposOwnerRepoDownloadsDownloadIDNoContent creates DeleteReposOwnerRepoDownloadsDownloadIDNoContent with default headers values
func NewDeleteReposOwnerRepoDownloadsDownloadIDNoContent() *DeleteReposOwnerRepoDownloadsDownloadIDNoContent {
	return &DeleteReposOwnerRepoDownloadsDownloadIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteReposOwnerRepoDownloadsDownloadIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteReposOwnerRepoDownloadsDownloadIDForbiddenCode is the HTTP code returned for type DeleteReposOwnerRepoDownloadsDownloadIDForbidden
const DeleteReposOwnerRepoDownloadsDownloadIDForbiddenCode int = 403

/*DeleteReposOwnerRepoDownloadsDownloadIDForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response deleteReposOwnerRepoDownloadsDownloadIdForbidden
*/
type DeleteReposOwnerRepoDownloadsDownloadIDForbidden struct {
}

// NewDeleteReposOwnerRepoDownloadsDownloadIDForbidden creates DeleteReposOwnerRepoDownloadsDownloadIDForbidden with default headers values
func NewDeleteReposOwnerRepoDownloadsDownloadIDForbidden() *DeleteReposOwnerRepoDownloadsDownloadIDForbidden {
	return &DeleteReposOwnerRepoDownloadsDownloadIDForbidden{}
}

// WriteResponse to the client
func (o *DeleteReposOwnerRepoDownloadsDownloadIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
