// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteReposOwnerRepoReleasesAssetsIDNoContentCode is the HTTP code returned for type DeleteReposOwnerRepoReleasesAssetsIDNoContent
const DeleteReposOwnerRepoReleasesAssetsIDNoContentCode int = 204

/*DeleteReposOwnerRepoReleasesAssetsIDNoContent No Content

swagger:response deleteReposOwnerRepoReleasesAssetsIdNoContent
*/
type DeleteReposOwnerRepoReleasesAssetsIDNoContent struct {
}

// NewDeleteReposOwnerRepoReleasesAssetsIDNoContent creates DeleteReposOwnerRepoReleasesAssetsIDNoContent with default headers values
func NewDeleteReposOwnerRepoReleasesAssetsIDNoContent() *DeleteReposOwnerRepoReleasesAssetsIDNoContent {
	return &DeleteReposOwnerRepoReleasesAssetsIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteReposOwnerRepoReleasesAssetsIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteReposOwnerRepoReleasesAssetsIDForbiddenCode is the HTTP code returned for type DeleteReposOwnerRepoReleasesAssetsIDForbidden
const DeleteReposOwnerRepoReleasesAssetsIDForbiddenCode int = 403

/*DeleteReposOwnerRepoReleasesAssetsIDForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response deleteReposOwnerRepoReleasesAssetsIdForbidden
*/
type DeleteReposOwnerRepoReleasesAssetsIDForbidden struct {
}

// NewDeleteReposOwnerRepoReleasesAssetsIDForbidden creates DeleteReposOwnerRepoReleasesAssetsIDForbidden with default headers values
func NewDeleteReposOwnerRepoReleasesAssetsIDForbidden() *DeleteReposOwnerRepoReleasesAssetsIDForbidden {
	return &DeleteReposOwnerRepoReleasesAssetsIDForbidden{}
}

// WriteResponse to the client
func (o *DeleteReposOwnerRepoReleasesAssetsIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
