// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteReposOwnerRepoCommentsCommentIDNoContentCode is the HTTP code returned for type DeleteReposOwnerRepoCommentsCommentIDNoContent
const DeleteReposOwnerRepoCommentsCommentIDNoContentCode int = 204

/*DeleteReposOwnerRepoCommentsCommentIDNoContent No content.


swagger:response deleteReposOwnerRepoCommentsCommentIdNoContent
*/
type DeleteReposOwnerRepoCommentsCommentIDNoContent struct {
}

// NewDeleteReposOwnerRepoCommentsCommentIDNoContent creates DeleteReposOwnerRepoCommentsCommentIDNoContent with default headers values
func NewDeleteReposOwnerRepoCommentsCommentIDNoContent() *DeleteReposOwnerRepoCommentsCommentIDNoContent {
	return &DeleteReposOwnerRepoCommentsCommentIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteReposOwnerRepoCommentsCommentIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteReposOwnerRepoCommentsCommentIDForbiddenCode is the HTTP code returned for type DeleteReposOwnerRepoCommentsCommentIDForbidden
const DeleteReposOwnerRepoCommentsCommentIDForbiddenCode int = 403

/*DeleteReposOwnerRepoCommentsCommentIDForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response deleteReposOwnerRepoCommentsCommentIdForbidden
*/
type DeleteReposOwnerRepoCommentsCommentIDForbidden struct {
}

// NewDeleteReposOwnerRepoCommentsCommentIDForbidden creates DeleteReposOwnerRepoCommentsCommentIDForbidden with default headers values
func NewDeleteReposOwnerRepoCommentsCommentIDForbidden() *DeleteReposOwnerRepoCommentsCommentIDForbidden {
	return &DeleteReposOwnerRepoCommentsCommentIDForbidden{}
}

// WriteResponse to the client
func (o *DeleteReposOwnerRepoCommentsCommentIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
