// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetReposOwnerRepoMilestonesHandlerFunc turns a function with the right signature into a get repos owner repo milestones handler
type GetReposOwnerRepoMilestonesHandlerFunc func(GetReposOwnerRepoMilestonesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetReposOwnerRepoMilestonesHandlerFunc) Handle(params GetReposOwnerRepoMilestonesParams) middleware.Responder {
	return fn(params)
}

// GetReposOwnerRepoMilestonesHandler interface for that can handle valid get repos owner repo milestones params
type GetReposOwnerRepoMilestonesHandler interface {
	Handle(GetReposOwnerRepoMilestonesParams) middleware.Responder
}

// NewGetReposOwnerRepoMilestones creates a new http.Handler for the get repos owner repo milestones operation
func NewGetReposOwnerRepoMilestones(ctx *middleware.Context, handler GetReposOwnerRepoMilestonesHandler) *GetReposOwnerRepoMilestones {
	return &GetReposOwnerRepoMilestones{Context: ctx, Handler: handler}
}

/*GetReposOwnerRepoMilestones swagger:route GET /repos/{owner}/{repo}/milestones getReposOwnerRepoMilestones

List milestones for a repository.

*/
type GetReposOwnerRepoMilestones struct {
	Context *middleware.Context
	Handler GetReposOwnerRepoMilestonesHandler
}

func (o *GetReposOwnerRepoMilestones) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetReposOwnerRepoMilestonesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
