// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// GetReposOwnerRepoContentsPathOKCode is the HTTP code returned for type GetReposOwnerRepoContentsPathOK
const GetReposOwnerRepoContentsPathOKCode int = 200

/*GetReposOwnerRepoContentsPathOK OK

swagger:response getReposOwnerRepoContentsPathOK
*/
type GetReposOwnerRepoContentsPathOK struct {

	/*
	  In: Body
	*/
	Payload *models.ContentsPath `json:"body,omitempty"`
}

// NewGetReposOwnerRepoContentsPathOK creates GetReposOwnerRepoContentsPathOK with default headers values
func NewGetReposOwnerRepoContentsPathOK() *GetReposOwnerRepoContentsPathOK {
	return &GetReposOwnerRepoContentsPathOK{}
}

// WithPayload adds the payload to the get repos owner repo contents path o k response
func (o *GetReposOwnerRepoContentsPathOK) WithPayload(payload *models.ContentsPath) *GetReposOwnerRepoContentsPathOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repos owner repo contents path o k response
func (o *GetReposOwnerRepoContentsPathOK) SetPayload(payload *models.ContentsPath) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReposOwnerRepoContentsPathOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetReposOwnerRepoContentsPathForbiddenCode is the HTTP code returned for type GetReposOwnerRepoContentsPathForbidden
const GetReposOwnerRepoContentsPathForbiddenCode int = 403

/*GetReposOwnerRepoContentsPathForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getReposOwnerRepoContentsPathForbidden
*/
type GetReposOwnerRepoContentsPathForbidden struct {
}

// NewGetReposOwnerRepoContentsPathForbidden creates GetReposOwnerRepoContentsPathForbidden with default headers values
func NewGetReposOwnerRepoContentsPathForbidden() *GetReposOwnerRepoContentsPathForbidden {
	return &GetReposOwnerRepoContentsPathForbidden{}
}

// WriteResponse to the client
func (o *GetReposOwnerRepoContentsPathForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
