// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetEmojisHandlerFunc turns a function with the right signature into a get emojis handler
type GetEmojisHandlerFunc func(GetEmojisParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEmojisHandlerFunc) Handle(params GetEmojisParams) middleware.Responder {
	return fn(params)
}

// GetEmojisHandler interface for that can handle valid get emojis params
type GetEmojisHandler interface {
	Handle(GetEmojisParams) middleware.Responder
}

// NewGetEmojis creates a new http.Handler for the get emojis operation
func NewGetEmojis(ctx *middleware.Context, handler GetEmojisHandler) *GetEmojis {
	return &GetEmojis{Context: ctx, Handler: handler}
}

/*GetEmojis swagger:route GET /emojis getEmojis

Lists all the emojis available to use on GitHub.

*/
type GetEmojis struct {
	Context *middleware.Context
	Handler GetEmojisHandler
}

func (o *GetEmojis) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetEmojisParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
