// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// GetUserSubscriptionsOKCode is the HTTP code returned for type GetUserSubscriptionsOK
const GetUserSubscriptionsOKCode int = 200

/*GetUserSubscriptionsOK OK

swagger:response getUserSubscriptionsOK
*/
type GetUserSubscriptionsOK struct {

	/*
	  In: Body
	*/
	Payload models.UserUserIDSubscribitions `json:"body,omitempty"`
}

// NewGetUserSubscriptionsOK creates GetUserSubscriptionsOK with default headers values
func NewGetUserSubscriptionsOK() *GetUserSubscriptionsOK {
	return &GetUserSubscriptionsOK{}
}

// WithPayload adds the payload to the get user subscriptions o k response
func (o *GetUserSubscriptionsOK) WithPayload(payload models.UserUserIDSubscribitions) *GetUserSubscriptionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user subscriptions o k response
func (o *GetUserSubscriptionsOK) SetPayload(payload models.UserUserIDSubscribitions) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserSubscriptionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.UserUserIDSubscribitions, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetUserSubscriptionsForbiddenCode is the HTTP code returned for type GetUserSubscriptionsForbidden
const GetUserSubscriptionsForbiddenCode int = 403

/*GetUserSubscriptionsForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getUserSubscriptionsForbidden
*/
type GetUserSubscriptionsForbidden struct {
}

// NewGetUserSubscriptionsForbidden creates GetUserSubscriptionsForbidden with default headers values
func NewGetUserSubscriptionsForbidden() *GetUserSubscriptionsForbidden {
	return &GetUserSubscriptionsForbidden{}
}

// WriteResponse to the client
func (o *GetUserSubscriptionsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
