// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetReposOwnerRepoIssuesCommentsCommentIDHandlerFunc turns a function with the right signature into a get repos owner repo issues comments comment ID handler
type GetReposOwnerRepoIssuesCommentsCommentIDHandlerFunc func(GetReposOwnerRepoIssuesCommentsCommentIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetReposOwnerRepoIssuesCommentsCommentIDHandlerFunc) Handle(params GetReposOwnerRepoIssuesCommentsCommentIDParams) middleware.Responder {
	return fn(params)
}

// GetReposOwnerRepoIssuesCommentsCommentIDHandler interface for that can handle valid get repos owner repo issues comments comment ID params
type GetReposOwnerRepoIssuesCommentsCommentIDHandler interface {
	Handle(GetReposOwnerRepoIssuesCommentsCommentIDParams) middleware.Responder
}

// NewGetReposOwnerRepoIssuesCommentsCommentID creates a new http.Handler for the get repos owner repo issues comments comment ID operation
func NewGetReposOwnerRepoIssuesCommentsCommentID(ctx *middleware.Context, handler GetReposOwnerRepoIssuesCommentsCommentIDHandler) *GetReposOwnerRepoIssuesCommentsCommentID {
	return &GetReposOwnerRepoIssuesCommentsCommentID{Context: ctx, Handler: handler}
}

/*GetReposOwnerRepoIssuesCommentsCommentID swagger:route GET /repos/{owner}/{repo}/issues/comments/{commentId} getReposOwnerRepoIssuesCommentsCommentId

Get a single comment.

*/
type GetReposOwnerRepoIssuesCommentsCommentID struct {
	Context *middleware.Context
	Handler GetReposOwnerRepoIssuesCommentsCommentIDHandler
}

func (o *GetReposOwnerRepoIssuesCommentsCommentID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetReposOwnerRepoIssuesCommentsCommentIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
