// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// GetReposOwnerRepoMilestonesNumberOKCode is the HTTP code returned for type GetReposOwnerRepoMilestonesNumberOK
const GetReposOwnerRepoMilestonesNumberOKCode int = 200

/*GetReposOwnerRepoMilestonesNumberOK OK

swagger:response getReposOwnerRepoMilestonesNumberOK
*/
type GetReposOwnerRepoMilestonesNumberOK struct {

	/*
	  In: Body
	*/
	Payload *models.Milestone `json:"body,omitempty"`
}

// NewGetReposOwnerRepoMilestonesNumberOK creates GetReposOwnerRepoMilestonesNumberOK with default headers values
func NewGetReposOwnerRepoMilestonesNumberOK() *GetReposOwnerRepoMilestonesNumberOK {
	return &GetReposOwnerRepoMilestonesNumberOK{}
}

// WithPayload adds the payload to the get repos owner repo milestones number o k response
func (o *GetReposOwnerRepoMilestonesNumberOK) WithPayload(payload *models.Milestone) *GetReposOwnerRepoMilestonesNumberOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repos owner repo milestones number o k response
func (o *GetReposOwnerRepoMilestonesNumberOK) SetPayload(payload *models.Milestone) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReposOwnerRepoMilestonesNumberOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetReposOwnerRepoMilestonesNumberForbiddenCode is the HTTP code returned for type GetReposOwnerRepoMilestonesNumberForbidden
const GetReposOwnerRepoMilestonesNumberForbiddenCode int = 403

/*GetReposOwnerRepoMilestonesNumberForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getReposOwnerRepoMilestonesNumberForbidden
*/
type GetReposOwnerRepoMilestonesNumberForbidden struct {
}

// NewGetReposOwnerRepoMilestonesNumberForbidden creates GetReposOwnerRepoMilestonesNumberForbidden with default headers values
func NewGetReposOwnerRepoMilestonesNumberForbidden() *GetReposOwnerRepoMilestonesNumberForbidden {
	return &GetReposOwnerRepoMilestonesNumberForbidden{}
}

// WriteResponse to the client
func (o *GetReposOwnerRepoMilestonesNumberForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
