// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetReposOwnerRepoDownloadsDownloadIDHandlerFunc turns a function with the right signature into a get repos owner repo downloads download ID handler
type GetReposOwnerRepoDownloadsDownloadIDHandlerFunc func(GetReposOwnerRepoDownloadsDownloadIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetReposOwnerRepoDownloadsDownloadIDHandlerFunc) Handle(params GetReposOwnerRepoDownloadsDownloadIDParams) middleware.Responder {
	return fn(params)
}

// GetReposOwnerRepoDownloadsDownloadIDHandler interface for that can handle valid get repos owner repo downloads download ID params
type GetReposOwnerRepoDownloadsDownloadIDHandler interface {
	Handle(GetReposOwnerRepoDownloadsDownloadIDParams) middleware.Responder
}

// NewGetReposOwnerRepoDownloadsDownloadID creates a new http.Handler for the get repos owner repo downloads download ID operation
func NewGetReposOwnerRepoDownloadsDownloadID(ctx *middleware.Context, handler GetReposOwnerRepoDownloadsDownloadIDHandler) *GetReposOwnerRepoDownloadsDownloadID {
	return &GetReposOwnerRepoDownloadsDownloadID{Context: ctx, Handler: handler}
}

/*GetReposOwnerRepoDownloadsDownloadID swagger:route GET /repos/{owner}/{repo}/downloads/{downloadId} getReposOwnerRepoDownloadsDownloadId

Deprecated. Get a single download.

*/
type GetReposOwnerRepoDownloadsDownloadID struct {
	Context *middleware.Context
	Handler GetReposOwnerRepoDownloadsDownloadIDHandler
}

func (o *GetReposOwnerRepoDownloadsDownloadID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetReposOwnerRepoDownloadsDownloadIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
