// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// GetReposOwnerRepoReleasesAssetsIDOKCode is the HTTP code returned for type GetReposOwnerRepoReleasesAssetsIDOK
const GetReposOwnerRepoReleasesAssetsIDOKCode int = 200

/*GetReposOwnerRepoReleasesAssetsIDOK OK

swagger:response getReposOwnerRepoReleasesAssetsIdOK
*/
type GetReposOwnerRepoReleasesAssetsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Asset `json:"body,omitempty"`
}

// NewGetReposOwnerRepoReleasesAssetsIDOK creates GetReposOwnerRepoReleasesAssetsIDOK with default headers values
func NewGetReposOwnerRepoReleasesAssetsIDOK() *GetReposOwnerRepoReleasesAssetsIDOK {
	return &GetReposOwnerRepoReleasesAssetsIDOK{}
}

// WithPayload adds the payload to the get repos owner repo releases assets Id o k response
func (o *GetReposOwnerRepoReleasesAssetsIDOK) WithPayload(payload *models.Asset) *GetReposOwnerRepoReleasesAssetsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repos owner repo releases assets Id o k response
func (o *GetReposOwnerRepoReleasesAssetsIDOK) SetPayload(payload *models.Asset) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReposOwnerRepoReleasesAssetsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetReposOwnerRepoReleasesAssetsIDForbiddenCode is the HTTP code returned for type GetReposOwnerRepoReleasesAssetsIDForbidden
const GetReposOwnerRepoReleasesAssetsIDForbiddenCode int = 403

/*GetReposOwnerRepoReleasesAssetsIDForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getReposOwnerRepoReleasesAssetsIdForbidden
*/
type GetReposOwnerRepoReleasesAssetsIDForbidden struct {
}

// NewGetReposOwnerRepoReleasesAssetsIDForbidden creates GetReposOwnerRepoReleasesAssetsIDForbidden with default headers values
func NewGetReposOwnerRepoReleasesAssetsIDForbidden() *GetReposOwnerRepoReleasesAssetsIDForbidden {
	return &GetReposOwnerRepoReleasesAssetsIDForbidden{}
}

// WriteResponse to the client
func (o *GetReposOwnerRepoReleasesAssetsIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
