// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// GetReposOwnerRepoEventsOKCode is the HTTP code returned for type GetReposOwnerRepoEventsOK
const GetReposOwnerRepoEventsOKCode int = 200

/*GetReposOwnerRepoEventsOK OK

swagger:response getReposOwnerRepoEventsOK
*/
type GetReposOwnerRepoEventsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Events `json:"body,omitempty"`
}

// NewGetReposOwnerRepoEventsOK creates GetReposOwnerRepoEventsOK with default headers values
func NewGetReposOwnerRepoEventsOK() *GetReposOwnerRepoEventsOK {
	return &GetReposOwnerRepoEventsOK{}
}

// WithPayload adds the payload to the get repos owner repo events o k response
func (o *GetReposOwnerRepoEventsOK) WithPayload(payload *models.Events) *GetReposOwnerRepoEventsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repos owner repo events o k response
func (o *GetReposOwnerRepoEventsOK) SetPayload(payload *models.Events) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReposOwnerRepoEventsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetReposOwnerRepoEventsForbiddenCode is the HTTP code returned for type GetReposOwnerRepoEventsForbidden
const GetReposOwnerRepoEventsForbiddenCode int = 403

/*GetReposOwnerRepoEventsForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getReposOwnerRepoEventsForbidden
*/
type GetReposOwnerRepoEventsForbidden struct {
}

// NewGetReposOwnerRepoEventsForbidden creates GetReposOwnerRepoEventsForbidden with default headers values
func NewGetReposOwnerRepoEventsForbidden() *GetReposOwnerRepoEventsForbidden {
	return &GetReposOwnerRepoEventsForbidden{}
}

// WriteResponse to the client
func (o *GetReposOwnerRepoEventsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
