// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetUserStarredHandlerFunc turns a function with the right signature into a get user starred handler
type GetUserStarredHandlerFunc func(GetUserStarredParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserStarredHandlerFunc) Handle(params GetUserStarredParams) middleware.Responder {
	return fn(params)
}

// GetUserStarredHandler interface for that can handle valid get user starred params
type GetUserStarredHandler interface {
	Handle(GetUserStarredParams) middleware.Responder
}

// NewGetUserStarred creates a new http.Handler for the get user starred operation
func NewGetUserStarred(ctx *middleware.Context, handler GetUserStarredHandler) *GetUserStarred {
	return &GetUserStarred{Context: ctx, Handler: handler}
}

/*GetUserStarred swagger:route GET /user/starred getUserStarred

List repositories being starred by the authenticated user.

*/
type GetUserStarred struct {
	Context *middleware.Context
	Handler GetUserStarredHandler
}

func (o *GetUserStarred) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUserStarredParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
