// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetReposOwnerRepoLanguagesHandlerFunc turns a function with the right signature into a get repos owner repo languages handler
type GetReposOwnerRepoLanguagesHandlerFunc func(GetReposOwnerRepoLanguagesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetReposOwnerRepoLanguagesHandlerFunc) Handle(params GetReposOwnerRepoLanguagesParams) middleware.Responder {
	return fn(params)
}

// GetReposOwnerRepoLanguagesHandler interface for that can handle valid get repos owner repo languages params
type GetReposOwnerRepoLanguagesHandler interface {
	Handle(GetReposOwnerRepoLanguagesParams) middleware.Responder
}

// NewGetReposOwnerRepoLanguages creates a new http.Handler for the get repos owner repo languages operation
func NewGetReposOwnerRepoLanguages(ctx *middleware.Context, handler GetReposOwnerRepoLanguagesHandler) *GetReposOwnerRepoLanguages {
	return &GetReposOwnerRepoLanguages{Context: ctx, Handler: handler}
}

/*GetReposOwnerRepoLanguages swagger:route GET /repos/{owner}/{repo}/languages getReposOwnerRepoLanguages

List languages.
List languages for the specified repository. The value on the right of a
language is the number of bytes of code written in that language.


*/
type GetReposOwnerRepoLanguages struct {
	Context *middleware.Context
	Handler GetReposOwnerRepoLanguagesHandler
}

func (o *GetReposOwnerRepoLanguages) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetReposOwnerRepoLanguagesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
