// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetReposOwnerRepoCollaboratorsHandlerFunc turns a function with the right signature into a get repos owner repo collaborators handler
type GetReposOwnerRepoCollaboratorsHandlerFunc func(GetReposOwnerRepoCollaboratorsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetReposOwnerRepoCollaboratorsHandlerFunc) Handle(params GetReposOwnerRepoCollaboratorsParams) middleware.Responder {
	return fn(params)
}

// GetReposOwnerRepoCollaboratorsHandler interface for that can handle valid get repos owner repo collaborators params
type GetReposOwnerRepoCollaboratorsHandler interface {
	Handle(GetReposOwnerRepoCollaboratorsParams) middleware.Responder
}

// NewGetReposOwnerRepoCollaborators creates a new http.Handler for the get repos owner repo collaborators operation
func NewGetReposOwnerRepoCollaborators(ctx *middleware.Context, handler GetReposOwnerRepoCollaboratorsHandler) *GetReposOwnerRepoCollaborators {
	return &GetReposOwnerRepoCollaborators{Context: ctx, Handler: handler}
}

/*GetReposOwnerRepoCollaborators swagger:route GET /repos/{owner}/{repo}/collaborators getReposOwnerRepoCollaborators

List.
When authenticating as an organization owner of an organization-owned
repository, all organization owners are included in the list of
collaborators. Otherwise, only users with access to the repository are
returned in the collaborators list.


*/
type GetReposOwnerRepoCollaborators struct {
	Context *middleware.Context
	Handler GetReposOwnerRepoCollaboratorsHandler
}

func (o *GetReposOwnerRepoCollaborators) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetReposOwnerRepoCollaboratorsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
