// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// GetReposOwnerRepoDeploymentsIDStatusesOKCode is the HTTP code returned for type GetReposOwnerRepoDeploymentsIDStatusesOK
const GetReposOwnerRepoDeploymentsIDStatusesOKCode int = 200

/*GetReposOwnerRepoDeploymentsIDStatusesOK OK

swagger:response getReposOwnerRepoDeploymentsIdStatusesOK
*/
type GetReposOwnerRepoDeploymentsIDStatusesOK struct {

	/*
	  In: Body
	*/
	Payload models.DeploymentStatuses `json:"body,omitempty"`
}

// NewGetReposOwnerRepoDeploymentsIDStatusesOK creates GetReposOwnerRepoDeploymentsIDStatusesOK with default headers values
func NewGetReposOwnerRepoDeploymentsIDStatusesOK() *GetReposOwnerRepoDeploymentsIDStatusesOK {
	return &GetReposOwnerRepoDeploymentsIDStatusesOK{}
}

// WithPayload adds the payload to the get repos owner repo deployments Id statuses o k response
func (o *GetReposOwnerRepoDeploymentsIDStatusesOK) WithPayload(payload models.DeploymentStatuses) *GetReposOwnerRepoDeploymentsIDStatusesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repos owner repo deployments Id statuses o k response
func (o *GetReposOwnerRepoDeploymentsIDStatusesOK) SetPayload(payload models.DeploymentStatuses) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReposOwnerRepoDeploymentsIDStatusesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.DeploymentStatuses, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetReposOwnerRepoDeploymentsIDStatusesForbiddenCode is the HTTP code returned for type GetReposOwnerRepoDeploymentsIDStatusesForbidden
const GetReposOwnerRepoDeploymentsIDStatusesForbiddenCode int = 403

/*GetReposOwnerRepoDeploymentsIDStatusesForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getReposOwnerRepoDeploymentsIdStatusesForbidden
*/
type GetReposOwnerRepoDeploymentsIDStatusesForbidden struct {
}

// NewGetReposOwnerRepoDeploymentsIDStatusesForbidden creates GetReposOwnerRepoDeploymentsIDStatusesForbidden with default headers values
func NewGetReposOwnerRepoDeploymentsIDStatusesForbidden() *GetReposOwnerRepoDeploymentsIDStatusesForbidden {
	return &GetReposOwnerRepoDeploymentsIDStatusesForbidden{}
}

// WriteResponse to the client
func (o *GetReposOwnerRepoDeploymentsIDStatusesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
