// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetReposOwnerRepoReleasesHandlerFunc turns a function with the right signature into a get repos owner repo releases handler
type GetReposOwnerRepoReleasesHandlerFunc func(GetReposOwnerRepoReleasesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetReposOwnerRepoReleasesHandlerFunc) Handle(params GetReposOwnerRepoReleasesParams) middleware.Responder {
	return fn(params)
}

// GetReposOwnerRepoReleasesHandler interface for that can handle valid get repos owner repo releases params
type GetReposOwnerRepoReleasesHandler interface {
	Handle(GetReposOwnerRepoReleasesParams) middleware.Responder
}

// NewGetReposOwnerRepoReleases creates a new http.Handler for the get repos owner repo releases operation
func NewGetReposOwnerRepoReleases(ctx *middleware.Context, handler GetReposOwnerRepoReleasesHandler) *GetReposOwnerRepoReleases {
	return &GetReposOwnerRepoReleases{Context: ctx, Handler: handler}
}

/*GetReposOwnerRepoReleases swagger:route GET /repos/{owner}/{repo}/releases getReposOwnerRepoReleases

Users with push access to the repository will receive all releases (i.e., published releases and draft releases). Users with pull access will receive published releases only

*/
type GetReposOwnerRepoReleases struct {
	Context *middleware.Context
	Handler GetReposOwnerRepoReleasesHandler
}

func (o *GetReposOwnerRepoReleases) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetReposOwnerRepoReleasesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
