// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// GetReposOwnerRepoGitRefsOKCode is the HTTP code returned for type GetReposOwnerRepoGitRefsOK
const GetReposOwnerRepoGitRefsOKCode int = 200

/*GetReposOwnerRepoGitRefsOK OK

swagger:response getReposOwnerRepoGitRefsOK
*/
type GetReposOwnerRepoGitRefsOK struct {

	/*
	  In: Body
	*/
	Payload models.Refs `json:"body,omitempty"`
}

// NewGetReposOwnerRepoGitRefsOK creates GetReposOwnerRepoGitRefsOK with default headers values
func NewGetReposOwnerRepoGitRefsOK() *GetReposOwnerRepoGitRefsOK {
	return &GetReposOwnerRepoGitRefsOK{}
}

// WithPayload adds the payload to the get repos owner repo git refs o k response
func (o *GetReposOwnerRepoGitRefsOK) WithPayload(payload models.Refs) *GetReposOwnerRepoGitRefsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repos owner repo git refs o k response
func (o *GetReposOwnerRepoGitRefsOK) SetPayload(payload models.Refs) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReposOwnerRepoGitRefsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Refs, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetReposOwnerRepoGitRefsForbiddenCode is the HTTP code returned for type GetReposOwnerRepoGitRefsForbidden
const GetReposOwnerRepoGitRefsForbiddenCode int = 403

/*GetReposOwnerRepoGitRefsForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getReposOwnerRepoGitRefsForbidden
*/
type GetReposOwnerRepoGitRefsForbidden struct {
}

// NewGetReposOwnerRepoGitRefsForbidden creates GetReposOwnerRepoGitRefsForbidden with default headers values
func NewGetReposOwnerRepoGitRefsForbidden() *GetReposOwnerRepoGitRefsForbidden {
	return &GetReposOwnerRepoGitRefsForbidden{}
}

// WriteResponse to the client
func (o *GetReposOwnerRepoGitRefsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
