// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// GetReposOwnerRepoCommitsOKCode is the HTTP code returned for type GetReposOwnerRepoCommitsOK
const GetReposOwnerRepoCommitsOKCode int = 200

/*GetReposOwnerRepoCommitsOK OK

swagger:response getReposOwnerRepoCommitsOK
*/
type GetReposOwnerRepoCommitsOK struct {

	/*
	  In: Body
	*/
	Payload models.Commits `json:"body,omitempty"`
}

// NewGetReposOwnerRepoCommitsOK creates GetReposOwnerRepoCommitsOK with default headers values
func NewGetReposOwnerRepoCommitsOK() *GetReposOwnerRepoCommitsOK {
	return &GetReposOwnerRepoCommitsOK{}
}

// WithPayload adds the payload to the get repos owner repo commits o k response
func (o *GetReposOwnerRepoCommitsOK) WithPayload(payload models.Commits) *GetReposOwnerRepoCommitsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repos owner repo commits o k response
func (o *GetReposOwnerRepoCommitsOK) SetPayload(payload models.Commits) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReposOwnerRepoCommitsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Commits, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetReposOwnerRepoCommitsForbiddenCode is the HTTP code returned for type GetReposOwnerRepoCommitsForbidden
const GetReposOwnerRepoCommitsForbiddenCode int = 403

/*GetReposOwnerRepoCommitsForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getReposOwnerRepoCommitsForbidden
*/
type GetReposOwnerRepoCommitsForbidden struct {
}

// NewGetReposOwnerRepoCommitsForbidden creates GetReposOwnerRepoCommitsForbidden with default headers values
func NewGetReposOwnerRepoCommitsForbidden() *GetReposOwnerRepoCommitsForbidden {
	return &GetReposOwnerRepoCommitsForbidden{}
}

// WriteResponse to the client
func (o *GetReposOwnerRepoCommitsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
