// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetNotificationsThreadsIDHandlerFunc turns a function with the right signature into a get notifications threads ID handler
type GetNotificationsThreadsIDHandlerFunc func(GetNotificationsThreadsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetNotificationsThreadsIDHandlerFunc) Handle(params GetNotificationsThreadsIDParams) middleware.Responder {
	return fn(params)
}

// GetNotificationsThreadsIDHandler interface for that can handle valid get notifications threads ID params
type GetNotificationsThreadsIDHandler interface {
	Handle(GetNotificationsThreadsIDParams) middleware.Responder
}

// NewGetNotificationsThreadsID creates a new http.Handler for the get notifications threads ID operation
func NewGetNotificationsThreadsID(ctx *middleware.Context, handler GetNotificationsThreadsIDHandler) *GetNotificationsThreadsID {
	return &GetNotificationsThreadsID{Context: ctx, Handler: handler}
}

/*GetNotificationsThreadsID swagger:route GET /notifications/threads/{id} getNotificationsThreadsId

View a single thread.

*/
type GetNotificationsThreadsID struct {
	Context *middleware.Context
	Handler GetNotificationsThreadsIDHandler
}

func (o *GetNotificationsThreadsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetNotificationsThreadsIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
