// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// GetReposOwnerRepoPullsNumberOKCode is the HTTP code returned for type GetReposOwnerRepoPullsNumberOK
const GetReposOwnerRepoPullsNumberOKCode int = 200

/*GetReposOwnerRepoPullsNumberOK OK

swagger:response getReposOwnerRepoPullsNumberOK
*/
type GetReposOwnerRepoPullsNumberOK struct {

	/*
	  In: Body
	*/
	Payload *models.PullRequest `json:"body,omitempty"`
}

// NewGetReposOwnerRepoPullsNumberOK creates GetReposOwnerRepoPullsNumberOK with default headers values
func NewGetReposOwnerRepoPullsNumberOK() *GetReposOwnerRepoPullsNumberOK {
	return &GetReposOwnerRepoPullsNumberOK{}
}

// WithPayload adds the payload to the get repos owner repo pulls number o k response
func (o *GetReposOwnerRepoPullsNumberOK) WithPayload(payload *models.PullRequest) *GetReposOwnerRepoPullsNumberOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repos owner repo pulls number o k response
func (o *GetReposOwnerRepoPullsNumberOK) SetPayload(payload *models.PullRequest) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReposOwnerRepoPullsNumberOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetReposOwnerRepoPullsNumberForbiddenCode is the HTTP code returned for type GetReposOwnerRepoPullsNumberForbidden
const GetReposOwnerRepoPullsNumberForbiddenCode int = 403

/*GetReposOwnerRepoPullsNumberForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getReposOwnerRepoPullsNumberForbidden
*/
type GetReposOwnerRepoPullsNumberForbidden struct {
}

// NewGetReposOwnerRepoPullsNumberForbidden creates GetReposOwnerRepoPullsNumberForbidden with default headers values
func NewGetReposOwnerRepoPullsNumberForbidden() *GetReposOwnerRepoPullsNumberForbidden {
	return &GetReposOwnerRepoPullsNumberForbidden{}
}

// WriteResponse to the client
func (o *GetReposOwnerRepoPullsNumberForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
