// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetSearchRepositoriesHandlerFunc turns a function with the right signature into a get search repositories handler
type GetSearchRepositoriesHandlerFunc func(GetSearchRepositoriesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSearchRepositoriesHandlerFunc) Handle(params GetSearchRepositoriesParams) middleware.Responder {
	return fn(params)
}

// GetSearchRepositoriesHandler interface for that can handle valid get search repositories params
type GetSearchRepositoriesHandler interface {
	Handle(GetSearchRepositoriesParams) middleware.Responder
}

// NewGetSearchRepositories creates a new http.Handler for the get search repositories operation
func NewGetSearchRepositories(ctx *middleware.Context, handler GetSearchRepositoriesHandler) *GetSearchRepositories {
	return &GetSearchRepositories{Context: ctx, Handler: handler}
}

/*GetSearchRepositories swagger:route GET /search/repositories getSearchRepositories

Search repositories.

*/
type GetSearchRepositories struct {
	Context *middleware.Context
	Handler GetSearchRepositoriesHandler
}

func (o *GetSearchRepositories) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSearchRepositoriesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
