// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// GetReposOwnerRepoIssuesCommentsOKCode is the HTTP code returned for type GetReposOwnerRepoIssuesCommentsOK
const GetReposOwnerRepoIssuesCommentsOKCode int = 200

/*GetReposOwnerRepoIssuesCommentsOK OK

swagger:response getReposOwnerRepoIssuesCommentsOK
*/
type GetReposOwnerRepoIssuesCommentsOK struct {

	/*
	  In: Body
	*/
	Payload models.IssuesComments `json:"body,omitempty"`
}

// NewGetReposOwnerRepoIssuesCommentsOK creates GetReposOwnerRepoIssuesCommentsOK with default headers values
func NewGetReposOwnerRepoIssuesCommentsOK() *GetReposOwnerRepoIssuesCommentsOK {
	return &GetReposOwnerRepoIssuesCommentsOK{}
}

// WithPayload adds the payload to the get repos owner repo issues comments o k response
func (o *GetReposOwnerRepoIssuesCommentsOK) WithPayload(payload models.IssuesComments) *GetReposOwnerRepoIssuesCommentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repos owner repo issues comments o k response
func (o *GetReposOwnerRepoIssuesCommentsOK) SetPayload(payload models.IssuesComments) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReposOwnerRepoIssuesCommentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.IssuesComments, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetReposOwnerRepoIssuesCommentsForbiddenCode is the HTTP code returned for type GetReposOwnerRepoIssuesCommentsForbidden
const GetReposOwnerRepoIssuesCommentsForbiddenCode int = 403

/*GetReposOwnerRepoIssuesCommentsForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getReposOwnerRepoIssuesCommentsForbidden
*/
type GetReposOwnerRepoIssuesCommentsForbidden struct {
}

// NewGetReposOwnerRepoIssuesCommentsForbidden creates GetReposOwnerRepoIssuesCommentsForbidden with default headers values
func NewGetReposOwnerRepoIssuesCommentsForbidden() *GetReposOwnerRepoIssuesCommentsForbidden {
	return &GetReposOwnerRepoIssuesCommentsForbidden{}
}

// WriteResponse to the client
func (o *GetReposOwnerRepoIssuesCommentsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
