// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// GetTeamsTeamIDMembersOKCode is the HTTP code returned for type GetTeamsTeamIDMembersOK
const GetTeamsTeamIDMembersOKCode int = 200

/*GetTeamsTeamIDMembersOK OK

swagger:response getTeamsTeamIdMembersOK
*/
type GetTeamsTeamIDMembersOK struct {

	/*
	  In: Body
	*/
	Payload models.Users `json:"body,omitempty"`
}

// NewGetTeamsTeamIDMembersOK creates GetTeamsTeamIDMembersOK with default headers values
func NewGetTeamsTeamIDMembersOK() *GetTeamsTeamIDMembersOK {
	return &GetTeamsTeamIDMembersOK{}
}

// WithPayload adds the payload to the get teams team Id members o k response
func (o *GetTeamsTeamIDMembersOK) WithPayload(payload models.Users) *GetTeamsTeamIDMembersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get teams team Id members o k response
func (o *GetTeamsTeamIDMembersOK) SetPayload(payload models.Users) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamsTeamIDMembersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Users, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetTeamsTeamIDMembersForbiddenCode is the HTTP code returned for type GetTeamsTeamIDMembersForbidden
const GetTeamsTeamIDMembersForbiddenCode int = 403

/*GetTeamsTeamIDMembersForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getTeamsTeamIdMembersForbidden
*/
type GetTeamsTeamIDMembersForbidden struct {
}

// NewGetTeamsTeamIDMembersForbidden creates GetTeamsTeamIDMembersForbidden with default headers values
func NewGetTeamsTeamIDMembersForbidden() *GetTeamsTeamIDMembersForbidden {
	return &GetTeamsTeamIDMembersForbidden{}
}

// WriteResponse to the client
func (o *GetTeamsTeamIDMembersForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
