// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetReposOwnerRepoIssuesEventsEventIDHandlerFunc turns a function with the right signature into a get repos owner repo issues events event ID handler
type GetReposOwnerRepoIssuesEventsEventIDHandlerFunc func(GetReposOwnerRepoIssuesEventsEventIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetReposOwnerRepoIssuesEventsEventIDHandlerFunc) Handle(params GetReposOwnerRepoIssuesEventsEventIDParams) middleware.Responder {
	return fn(params)
}

// GetReposOwnerRepoIssuesEventsEventIDHandler interface for that can handle valid get repos owner repo issues events event ID params
type GetReposOwnerRepoIssuesEventsEventIDHandler interface {
	Handle(GetReposOwnerRepoIssuesEventsEventIDParams) middleware.Responder
}

// NewGetReposOwnerRepoIssuesEventsEventID creates a new http.Handler for the get repos owner repo issues events event ID operation
func NewGetReposOwnerRepoIssuesEventsEventID(ctx *middleware.Context, handler GetReposOwnerRepoIssuesEventsEventIDHandler) *GetReposOwnerRepoIssuesEventsEventID {
	return &GetReposOwnerRepoIssuesEventsEventID{Context: ctx, Handler: handler}
}

/*GetReposOwnerRepoIssuesEventsEventID swagger:route GET /repos/{owner}/{repo}/issues/events/{eventId} getReposOwnerRepoIssuesEventsEventId

Get a single event.

*/
type GetReposOwnerRepoIssuesEventsEventID struct {
	Context *middleware.Context
	Handler GetReposOwnerRepoIssuesEventsEventIDHandler
}

func (o *GetReposOwnerRepoIssuesEventsEventID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetReposOwnerRepoIssuesEventsEventIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
