// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetUserFollowersHandlerFunc turns a function with the right signature into a get user followers handler
type GetUserFollowersHandlerFunc func(GetUserFollowersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserFollowersHandlerFunc) Handle(params GetUserFollowersParams) middleware.Responder {
	return fn(params)
}

// GetUserFollowersHandler interface for that can handle valid get user followers params
type GetUserFollowersHandler interface {
	Handle(GetUserFollowersParams) middleware.Responder
}

// NewGetUserFollowers creates a new http.Handler for the get user followers operation
func NewGetUserFollowers(ctx *middleware.Context, handler GetUserFollowersHandler) *GetUserFollowers {
	return &GetUserFollowers{Context: ctx, Handler: handler}
}

/*GetUserFollowers swagger:route GET /user/followers getUserFollowers

List the authenticated user's followers

*/
type GetUserFollowers struct {
	Context *middleware.Context
	Handler GetUserFollowersHandler
}

func (o *GetUserFollowers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUserFollowersParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
