// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTeamsTeamIDReposOwnerRepoForbiddenCode is the HTTP code returned for type GetTeamsTeamIDReposOwnerRepoForbidden
const GetTeamsTeamIDReposOwnerRepoForbiddenCode int = 403

/*GetTeamsTeamIDReposOwnerRepoForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getTeamsTeamIdReposOwnerRepoForbidden
*/
type GetTeamsTeamIDReposOwnerRepoForbidden struct {
}

// NewGetTeamsTeamIDReposOwnerRepoForbidden creates GetTeamsTeamIDReposOwnerRepoForbidden with default headers values
func NewGetTeamsTeamIDReposOwnerRepoForbidden() *GetTeamsTeamIDReposOwnerRepoForbidden {
	return &GetTeamsTeamIDReposOwnerRepoForbidden{}
}

// WriteResponse to the client
func (o *GetTeamsTeamIDReposOwnerRepoForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
