// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetReposOwnerRepoTagsHandlerFunc turns a function with the right signature into a get repos owner repo tags handler
type GetReposOwnerRepoTagsHandlerFunc func(GetReposOwnerRepoTagsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetReposOwnerRepoTagsHandlerFunc) Handle(params GetReposOwnerRepoTagsParams) middleware.Responder {
	return fn(params)
}

// GetReposOwnerRepoTagsHandler interface for that can handle valid get repos owner repo tags params
type GetReposOwnerRepoTagsHandler interface {
	Handle(GetReposOwnerRepoTagsParams) middleware.Responder
}

// NewGetReposOwnerRepoTags creates a new http.Handler for the get repos owner repo tags operation
func NewGetReposOwnerRepoTags(ctx *middleware.Context, handler GetReposOwnerRepoTagsHandler) *GetReposOwnerRepoTags {
	return &GetReposOwnerRepoTags{Context: ctx, Handler: handler}
}

/*GetReposOwnerRepoTags swagger:route GET /repos/{owner}/{repo}/tags getReposOwnerRepoTags

Get list of tags.

*/
type GetReposOwnerRepoTags struct {
	Context *middleware.Context
	Handler GetReposOwnerRepoTagsHandler
}

func (o *GetReposOwnerRepoTags) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetReposOwnerRepoTagsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
