// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// GetUsersUsernameOrgsOKCode is the HTTP code returned for type GetUsersUsernameOrgsOK
const GetUsersUsernameOrgsOKCode int = 200

/*GetUsersUsernameOrgsOK OK

swagger:response getUsersUsernameOrgsOK
*/
type GetUsersUsernameOrgsOK struct {

	/*
	  In: Body
	*/
	Payload models.Gitignore `json:"body,omitempty"`
}

// NewGetUsersUsernameOrgsOK creates GetUsersUsernameOrgsOK with default headers values
func NewGetUsersUsernameOrgsOK() *GetUsersUsernameOrgsOK {
	return &GetUsersUsernameOrgsOK{}
}

// WithPayload adds the payload to the get users username orgs o k response
func (o *GetUsersUsernameOrgsOK) WithPayload(payload models.Gitignore) *GetUsersUsernameOrgsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users username orgs o k response
func (o *GetUsersUsernameOrgsOK) SetPayload(payload models.Gitignore) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersUsernameOrgsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Gitignore, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetUsersUsernameOrgsForbiddenCode is the HTTP code returned for type GetUsersUsernameOrgsForbidden
const GetUsersUsernameOrgsForbiddenCode int = 403

/*GetUsersUsernameOrgsForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getUsersUsernameOrgsForbidden
*/
type GetUsersUsernameOrgsForbidden struct {
}

// NewGetUsersUsernameOrgsForbidden creates GetUsersUsernameOrgsForbidden with default headers values
func NewGetUsersUsernameOrgsForbidden() *GetUsersUsernameOrgsForbidden {
	return &GetUsersUsernameOrgsForbidden{}
}

// WriteResponse to the client
func (o *GetUsersUsernameOrgsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
