// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// GetReposOwnerRepoIssuesNumberLabelsOKCode is the HTTP code returned for type GetReposOwnerRepoIssuesNumberLabelsOK
const GetReposOwnerRepoIssuesNumberLabelsOKCode int = 200

/*GetReposOwnerRepoIssuesNumberLabelsOK OK

swagger:response getReposOwnerRepoIssuesNumberLabelsOK
*/
type GetReposOwnerRepoIssuesNumberLabelsOK struct {

	/*
	  In: Body
	*/
	Payload models.Labels `json:"body,omitempty"`
}

// NewGetReposOwnerRepoIssuesNumberLabelsOK creates GetReposOwnerRepoIssuesNumberLabelsOK with default headers values
func NewGetReposOwnerRepoIssuesNumberLabelsOK() *GetReposOwnerRepoIssuesNumberLabelsOK {
	return &GetReposOwnerRepoIssuesNumberLabelsOK{}
}

// WithPayload adds the payload to the get repos owner repo issues number labels o k response
func (o *GetReposOwnerRepoIssuesNumberLabelsOK) WithPayload(payload models.Labels) *GetReposOwnerRepoIssuesNumberLabelsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repos owner repo issues number labels o k response
func (o *GetReposOwnerRepoIssuesNumberLabelsOK) SetPayload(payload models.Labels) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReposOwnerRepoIssuesNumberLabelsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Labels, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetReposOwnerRepoIssuesNumberLabelsForbiddenCode is the HTTP code returned for type GetReposOwnerRepoIssuesNumberLabelsForbidden
const GetReposOwnerRepoIssuesNumberLabelsForbiddenCode int = 403

/*GetReposOwnerRepoIssuesNumberLabelsForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getReposOwnerRepoIssuesNumberLabelsForbidden
*/
type GetReposOwnerRepoIssuesNumberLabelsForbidden struct {
}

// NewGetReposOwnerRepoIssuesNumberLabelsForbidden creates GetReposOwnerRepoIssuesNumberLabelsForbidden with default headers values
func NewGetReposOwnerRepoIssuesNumberLabelsForbidden() *GetReposOwnerRepoIssuesNumberLabelsForbidden {
	return &GetReposOwnerRepoIssuesNumberLabelsForbidden{}
}

// WriteResponse to the client
func (o *GetReposOwnerRepoIssuesNumberLabelsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
