// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetOrgsOrgEventsHandlerFunc turns a function with the right signature into a get orgs org events handler
type GetOrgsOrgEventsHandlerFunc func(GetOrgsOrgEventsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOrgsOrgEventsHandlerFunc) Handle(params GetOrgsOrgEventsParams) middleware.Responder {
	return fn(params)
}

// GetOrgsOrgEventsHandler interface for that can handle valid get orgs org events params
type GetOrgsOrgEventsHandler interface {
	Handle(GetOrgsOrgEventsParams) middleware.Responder
}

// NewGetOrgsOrgEvents creates a new http.Handler for the get orgs org events operation
func NewGetOrgsOrgEvents(ctx *middleware.Context, handler GetOrgsOrgEventsHandler) *GetOrgsOrgEvents {
	return &GetOrgsOrgEvents{Context: ctx, Handler: handler}
}

/*GetOrgsOrgEvents swagger:route GET /orgs/{org}/events getOrgsOrgEvents

List public events for an organization.

*/
type GetOrgsOrgEvents struct {
	Context *middleware.Context
	Handler GetOrgsOrgEventsHandler
}

func (o *GetOrgsOrgEvents) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetOrgsOrgEventsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
