// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTeamsTeamIDMembersUsernameNoContentCode is the HTTP code returned for type GetTeamsTeamIDMembersUsernameNoContent
const GetTeamsTeamIDMembersUsernameNoContentCode int = 204

/*GetTeamsTeamIDMembersUsernameNoContent User is a member.

swagger:response getTeamsTeamIdMembersUsernameNoContent
*/
type GetTeamsTeamIDMembersUsernameNoContent struct {
}

// NewGetTeamsTeamIDMembersUsernameNoContent creates GetTeamsTeamIDMembersUsernameNoContent with default headers values
func NewGetTeamsTeamIDMembersUsernameNoContent() *GetTeamsTeamIDMembersUsernameNoContent {
	return &GetTeamsTeamIDMembersUsernameNoContent{}
}

// WriteResponse to the client
func (o *GetTeamsTeamIDMembersUsernameNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetTeamsTeamIDMembersUsernameForbiddenCode is the HTTP code returned for type GetTeamsTeamIDMembersUsernameForbidden
const GetTeamsTeamIDMembersUsernameForbiddenCode int = 403

/*GetTeamsTeamIDMembersUsernameForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getTeamsTeamIdMembersUsernameForbidden
*/
type GetTeamsTeamIDMembersUsernameForbidden struct {
}

// NewGetTeamsTeamIDMembersUsernameForbidden creates GetTeamsTeamIDMembersUsernameForbidden with default headers values
func NewGetTeamsTeamIDMembersUsernameForbidden() *GetTeamsTeamIDMembersUsernameForbidden {
	return &GetTeamsTeamIDMembersUsernameForbidden{}
}

// WriteResponse to the client
func (o *GetTeamsTeamIDMembersUsernameForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetTeamsTeamIDMembersUsernameNotFoundCode is the HTTP code returned for type GetTeamsTeamIDMembersUsernameNotFound
const GetTeamsTeamIDMembersUsernameNotFoundCode int = 404

/*GetTeamsTeamIDMembersUsernameNotFound User is not a member.

swagger:response getTeamsTeamIdMembersUsernameNotFound
*/
type GetTeamsTeamIDMembersUsernameNotFound struct {
}

// NewGetTeamsTeamIDMembersUsernameNotFound creates GetTeamsTeamIDMembersUsernameNotFound with default headers values
func NewGetTeamsTeamIDMembersUsernameNotFound() *GetTeamsTeamIDMembersUsernameNotFound {
	return &GetTeamsTeamIDMembersUsernameNotFound{}
}

// WriteResponse to the client
func (o *GetTeamsTeamIDMembersUsernameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
