// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// GetReposOwnerRepoContributorsOKCode is the HTTP code returned for type GetReposOwnerRepoContributorsOK
const GetReposOwnerRepoContributorsOKCode int = 200

/*GetReposOwnerRepoContributorsOK OK

swagger:response getReposOwnerRepoContributorsOK
*/
type GetReposOwnerRepoContributorsOK struct {

	/*
	  In: Body
	*/
	Payload models.Contributors `json:"body,omitempty"`
}

// NewGetReposOwnerRepoContributorsOK creates GetReposOwnerRepoContributorsOK with default headers values
func NewGetReposOwnerRepoContributorsOK() *GetReposOwnerRepoContributorsOK {
	return &GetReposOwnerRepoContributorsOK{}
}

// WithPayload adds the payload to the get repos owner repo contributors o k response
func (o *GetReposOwnerRepoContributorsOK) WithPayload(payload models.Contributors) *GetReposOwnerRepoContributorsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repos owner repo contributors o k response
func (o *GetReposOwnerRepoContributorsOK) SetPayload(payload models.Contributors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReposOwnerRepoContributorsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Contributors, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetReposOwnerRepoContributorsForbiddenCode is the HTTP code returned for type GetReposOwnerRepoContributorsForbidden
const GetReposOwnerRepoContributorsForbiddenCode int = 403

/*GetReposOwnerRepoContributorsForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getReposOwnerRepoContributorsForbidden
*/
type GetReposOwnerRepoContributorsForbidden struct {
}

// NewGetReposOwnerRepoContributorsForbidden creates GetReposOwnerRepoContributorsForbidden with default headers values
func NewGetReposOwnerRepoContributorsForbidden() *GetReposOwnerRepoContributorsForbidden {
	return &GetReposOwnerRepoContributorsForbidden{}
}

// WriteResponse to the client
func (o *GetReposOwnerRepoContributorsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
