// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// GetReposOwnerRepoCollaboratorsOKCode is the HTTP code returned for type GetReposOwnerRepoCollaboratorsOK
const GetReposOwnerRepoCollaboratorsOKCode int = 200

/*GetReposOwnerRepoCollaboratorsOK OK

swagger:response getReposOwnerRepoCollaboratorsOK
*/
type GetReposOwnerRepoCollaboratorsOK struct {

	/*
	  In: Body
	*/
	Payload models.Users `json:"body,omitempty"`
}

// NewGetReposOwnerRepoCollaboratorsOK creates GetReposOwnerRepoCollaboratorsOK with default headers values
func NewGetReposOwnerRepoCollaboratorsOK() *GetReposOwnerRepoCollaboratorsOK {
	return &GetReposOwnerRepoCollaboratorsOK{}
}

// WithPayload adds the payload to the get repos owner repo collaborators o k response
func (o *GetReposOwnerRepoCollaboratorsOK) WithPayload(payload models.Users) *GetReposOwnerRepoCollaboratorsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repos owner repo collaborators o k response
func (o *GetReposOwnerRepoCollaboratorsOK) SetPayload(payload models.Users) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReposOwnerRepoCollaboratorsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Users, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetReposOwnerRepoCollaboratorsForbiddenCode is the HTTP code returned for type GetReposOwnerRepoCollaboratorsForbidden
const GetReposOwnerRepoCollaboratorsForbiddenCode int = 403

/*GetReposOwnerRepoCollaboratorsForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getReposOwnerRepoCollaboratorsForbidden
*/
type GetReposOwnerRepoCollaboratorsForbidden struct {
}

// NewGetReposOwnerRepoCollaboratorsForbidden creates GetReposOwnerRepoCollaboratorsForbidden with default headers values
func NewGetReposOwnerRepoCollaboratorsForbidden() *GetReposOwnerRepoCollaboratorsForbidden {
	return &GetReposOwnerRepoCollaboratorsForbidden{}
}

// WriteResponse to the client
func (o *GetReposOwnerRepoCollaboratorsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
