// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// GetReposOwnerRepoGitCommitsShaCodeOKCode is the HTTP code returned for type GetReposOwnerRepoGitCommitsShaCodeOK
const GetReposOwnerRepoGitCommitsShaCodeOKCode int = 200

/*GetReposOwnerRepoGitCommitsShaCodeOK OK

swagger:response getReposOwnerRepoGitCommitsShaCodeOK
*/
type GetReposOwnerRepoGitCommitsShaCodeOK struct {

	/*
	  In: Body
	*/
	Payload *models.RepoCommit `json:"body,omitempty"`
}

// NewGetReposOwnerRepoGitCommitsShaCodeOK creates GetReposOwnerRepoGitCommitsShaCodeOK with default headers values
func NewGetReposOwnerRepoGitCommitsShaCodeOK() *GetReposOwnerRepoGitCommitsShaCodeOK {
	return &GetReposOwnerRepoGitCommitsShaCodeOK{}
}

// WithPayload adds the payload to the get repos owner repo git commits sha code o k response
func (o *GetReposOwnerRepoGitCommitsShaCodeOK) WithPayload(payload *models.RepoCommit) *GetReposOwnerRepoGitCommitsShaCodeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repos owner repo git commits sha code o k response
func (o *GetReposOwnerRepoGitCommitsShaCodeOK) SetPayload(payload *models.RepoCommit) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReposOwnerRepoGitCommitsShaCodeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetReposOwnerRepoGitCommitsShaCodeForbiddenCode is the HTTP code returned for type GetReposOwnerRepoGitCommitsShaCodeForbidden
const GetReposOwnerRepoGitCommitsShaCodeForbiddenCode int = 403

/*GetReposOwnerRepoGitCommitsShaCodeForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getReposOwnerRepoGitCommitsShaCodeForbidden
*/
type GetReposOwnerRepoGitCommitsShaCodeForbidden struct {
}

// NewGetReposOwnerRepoGitCommitsShaCodeForbidden creates GetReposOwnerRepoGitCommitsShaCodeForbidden with default headers values
func NewGetReposOwnerRepoGitCommitsShaCodeForbidden() *GetReposOwnerRepoGitCommitsShaCodeForbidden {
	return &GetReposOwnerRepoGitCommitsShaCodeForbidden{}
}

// WriteResponse to the client
func (o *GetReposOwnerRepoGitCommitsShaCodeForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
