// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// GetOrgsOrgIssuesURL generates an URL for the get orgs org issues operation
type GetOrgsOrgIssuesURL struct {
	Org string

	Direction string
	Filter    string
	Labels    string
	Since     *string
	Sort      string
	State     string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetOrgsOrgIssuesURL) WithBasePath(bp string) *GetOrgsOrgIssuesURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetOrgsOrgIssuesURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetOrgsOrgIssuesURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/orgs/{org}/issues"

	org := o.Org
	if org != "" {
		_path = strings.Replace(_path, "{org}", org, -1)
	} else {
		return nil, errors.New("Org is required on GetOrgsOrgIssuesURL")
	}
	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/"
	}
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	direction := o.Direction
	if direction != "" {
		qs.Set("direction", direction)
	}

	filter := o.Filter
	if filter != "" {
		qs.Set("filter", filter)
	}

	labels := o.Labels
	if labels != "" {
		qs.Set("labels", labels)
	}

	var since string
	if o.Since != nil {
		since = *o.Since
	}
	if since != "" {
		qs.Set("since", since)
	}

	sort := o.Sort
	if sort != "" {
		qs.Set("sort", sort)
	}

	state := o.State
	if state != "" {
		qs.Set("state", state)
	}

	result.RawQuery = qs.Encode()

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetOrgsOrgIssuesURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetOrgsOrgIssuesURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetOrgsOrgIssuesURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetOrgsOrgIssuesURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetOrgsOrgIssuesURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetOrgsOrgIssuesURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
