// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// GetUserFollowingOKCode is the HTTP code returned for type GetUserFollowingOK
const GetUserFollowingOKCode int = 200

/*GetUserFollowingOK OK

swagger:response getUserFollowingOK
*/
type GetUserFollowingOK struct {

	/*
	  In: Body
	*/
	Payload models.Users `json:"body,omitempty"`
}

// NewGetUserFollowingOK creates GetUserFollowingOK with default headers values
func NewGetUserFollowingOK() *GetUserFollowingOK {
	return &GetUserFollowingOK{}
}

// WithPayload adds the payload to the get user following o k response
func (o *GetUserFollowingOK) WithPayload(payload models.Users) *GetUserFollowingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user following o k response
func (o *GetUserFollowingOK) SetPayload(payload models.Users) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserFollowingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Users, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetUserFollowingForbiddenCode is the HTTP code returned for type GetUserFollowingForbidden
const GetUserFollowingForbiddenCode int = 403

/*GetUserFollowingForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getUserFollowingForbidden
*/
type GetUserFollowingForbidden struct {
}

// NewGetUserFollowingForbidden creates GetUserFollowingForbidden with default headers values
func NewGetUserFollowingForbidden() *GetUserFollowingForbidden {
	return &GetUserFollowingForbidden{}
}

// WriteResponse to the client
func (o *GetUserFollowingForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
