// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetOrgsOrgPublicMembersUsernameHandlerFunc turns a function with the right signature into a get orgs org public members username handler
type GetOrgsOrgPublicMembersUsernameHandlerFunc func(GetOrgsOrgPublicMembersUsernameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOrgsOrgPublicMembersUsernameHandlerFunc) Handle(params GetOrgsOrgPublicMembersUsernameParams) middleware.Responder {
	return fn(params)
}

// GetOrgsOrgPublicMembersUsernameHandler interface for that can handle valid get orgs org public members username params
type GetOrgsOrgPublicMembersUsernameHandler interface {
	Handle(GetOrgsOrgPublicMembersUsernameParams) middleware.Responder
}

// NewGetOrgsOrgPublicMembersUsername creates a new http.Handler for the get orgs org public members username operation
func NewGetOrgsOrgPublicMembersUsername(ctx *middleware.Context, handler GetOrgsOrgPublicMembersUsernameHandler) *GetOrgsOrgPublicMembersUsername {
	return &GetOrgsOrgPublicMembersUsername{Context: ctx, Handler: handler}
}

/*GetOrgsOrgPublicMembersUsername swagger:route GET /orgs/{org}/public_members/{username} getOrgsOrgPublicMembersUsername

Check public membership.

*/
type GetOrgsOrgPublicMembersUsername struct {
	Context *middleware.Context
	Handler GetOrgsOrgPublicMembersUsernameHandler
}

func (o *GetOrgsOrgPublicMembersUsername) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetOrgsOrgPublicMembersUsernameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
