// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetUsersUsernameFollowingTargetUserNoContentCode is the HTTP code returned for type GetUsersUsernameFollowingTargetUserNoContent
const GetUsersUsernameFollowingTargetUserNoContentCode int = 204

/*GetUsersUsernameFollowingTargetUserNoContent Response if user follows target user.

swagger:response getUsersUsernameFollowingTargetUserNoContent
*/
type GetUsersUsernameFollowingTargetUserNoContent struct {
}

// NewGetUsersUsernameFollowingTargetUserNoContent creates GetUsersUsernameFollowingTargetUserNoContent with default headers values
func NewGetUsersUsernameFollowingTargetUserNoContent() *GetUsersUsernameFollowingTargetUserNoContent {
	return &GetUsersUsernameFollowingTargetUserNoContent{}
}

// WriteResponse to the client
func (o *GetUsersUsernameFollowingTargetUserNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetUsersUsernameFollowingTargetUserForbiddenCode is the HTTP code returned for type GetUsersUsernameFollowingTargetUserForbidden
const GetUsersUsernameFollowingTargetUserForbiddenCode int = 403

/*GetUsersUsernameFollowingTargetUserForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response getUsersUsernameFollowingTargetUserForbidden
*/
type GetUsersUsernameFollowingTargetUserForbidden struct {
}

// NewGetUsersUsernameFollowingTargetUserForbidden creates GetUsersUsernameFollowingTargetUserForbidden with default headers values
func NewGetUsersUsernameFollowingTargetUserForbidden() *GetUsersUsernameFollowingTargetUserForbidden {
	return &GetUsersUsernameFollowingTargetUserForbidden{}
}

// WriteResponse to the client
func (o *GetUsersUsernameFollowingTargetUserForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetUsersUsernameFollowingTargetUserNotFoundCode is the HTTP code returned for type GetUsersUsernameFollowingTargetUserNotFound
const GetUsersUsernameFollowingTargetUserNotFoundCode int = 404

/*GetUsersUsernameFollowingTargetUserNotFound Response if user does not follow target user.

swagger:response getUsersUsernameFollowingTargetUserNotFound
*/
type GetUsersUsernameFollowingTargetUserNotFound struct {
}

// NewGetUsersUsernameFollowingTargetUserNotFound creates GetUsersUsernameFollowingTargetUserNotFound with default headers values
func NewGetUsersUsernameFollowingTargetUserNotFound() *GetUsersUsernameFollowingTargetUserNotFound {
	return &GetUsersUsernameFollowingTargetUserNotFound{}
}

// WriteResponse to the client
func (o *GetUsersUsernameFollowingTargetUserNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
