// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetReposOwnerRepoGitTagsShaCodeHandlerFunc turns a function with the right signature into a get repos owner repo git tags sha code handler
type GetReposOwnerRepoGitTagsShaCodeHandlerFunc func(GetReposOwnerRepoGitTagsShaCodeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetReposOwnerRepoGitTagsShaCodeHandlerFunc) Handle(params GetReposOwnerRepoGitTagsShaCodeParams) middleware.Responder {
	return fn(params)
}

// GetReposOwnerRepoGitTagsShaCodeHandler interface for that can handle valid get repos owner repo git tags sha code params
type GetReposOwnerRepoGitTagsShaCodeHandler interface {
	Handle(GetReposOwnerRepoGitTagsShaCodeParams) middleware.Responder
}

// NewGetReposOwnerRepoGitTagsShaCode creates a new http.Handler for the get repos owner repo git tags sha code operation
func NewGetReposOwnerRepoGitTagsShaCode(ctx *middleware.Context, handler GetReposOwnerRepoGitTagsShaCodeHandler) *GetReposOwnerRepoGitTagsShaCode {
	return &GetReposOwnerRepoGitTagsShaCode{Context: ctx, Handler: handler}
}

/*GetReposOwnerRepoGitTagsShaCode swagger:route GET /repos/{owner}/{repo}/git/tags/{shaCode} getReposOwnerRepoGitTagsShaCode

Get a Tag.

*/
type GetReposOwnerRepoGitTagsShaCode struct {
	Context *middleware.Context
	Handler GetReposOwnerRepoGitTagsShaCodeHandler
}

func (o *GetReposOwnerRepoGitTagsShaCode) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetReposOwnerRepoGitTagsShaCodeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
