// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PatchReposOwnerRepoMilestonesNumberHandlerFunc turns a function with the right signature into a patch repos owner repo milestones number handler
type PatchReposOwnerRepoMilestonesNumberHandlerFunc func(PatchReposOwnerRepoMilestonesNumberParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchReposOwnerRepoMilestonesNumberHandlerFunc) Handle(params PatchReposOwnerRepoMilestonesNumberParams) middleware.Responder {
	return fn(params)
}

// PatchReposOwnerRepoMilestonesNumberHandler interface for that can handle valid patch repos owner repo milestones number params
type PatchReposOwnerRepoMilestonesNumberHandler interface {
	Handle(PatchReposOwnerRepoMilestonesNumberParams) middleware.Responder
}

// NewPatchReposOwnerRepoMilestonesNumber creates a new http.Handler for the patch repos owner repo milestones number operation
func NewPatchReposOwnerRepoMilestonesNumber(ctx *middleware.Context, handler PatchReposOwnerRepoMilestonesNumberHandler) *PatchReposOwnerRepoMilestonesNumber {
	return &PatchReposOwnerRepoMilestonesNumber{Context: ctx, Handler: handler}
}

/*PatchReposOwnerRepoMilestonesNumber swagger:route PATCH /repos/{owner}/{repo}/milestones/{number} patchReposOwnerRepoMilestonesNumber

Update a milestone.

*/
type PatchReposOwnerRepoMilestonesNumber struct {
	Context *middleware.Context
	Handler PatchReposOwnerRepoMilestonesNumberHandler
}

func (o *PatchReposOwnerRepoMilestonesNumber) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchReposOwnerRepoMilestonesNumberParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
