// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// PatchOrgsOrgOKCode is the HTTP code returned for type PatchOrgsOrgOK
const PatchOrgsOrgOKCode int = 200

/*PatchOrgsOrgOK OK

swagger:response patchOrgsOrgOK
*/
type PatchOrgsOrgOK struct {

	/*
	  In: Body
	*/
	Payload *models.Organization `json:"body,omitempty"`
}

// NewPatchOrgsOrgOK creates PatchOrgsOrgOK with default headers values
func NewPatchOrgsOrgOK() *PatchOrgsOrgOK {
	return &PatchOrgsOrgOK{}
}

// WithPayload adds the payload to the patch orgs org o k response
func (o *PatchOrgsOrgOK) WithPayload(payload *models.Organization) *PatchOrgsOrgOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch orgs org o k response
func (o *PatchOrgsOrgOK) SetPayload(payload *models.Organization) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchOrgsOrgOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchOrgsOrgForbiddenCode is the HTTP code returned for type PatchOrgsOrgForbidden
const PatchOrgsOrgForbiddenCode int = 403

/*PatchOrgsOrgForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response patchOrgsOrgForbidden
*/
type PatchOrgsOrgForbidden struct {
}

// NewPatchOrgsOrgForbidden creates PatchOrgsOrgForbidden with default headers values
func NewPatchOrgsOrgForbidden() *PatchOrgsOrgForbidden {
	return &PatchOrgsOrgForbidden{}
}

// WriteResponse to the client
func (o *PatchOrgsOrgForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
