// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PatchReposOwnerRepoPullsNumberHandlerFunc turns a function with the right signature into a patch repos owner repo pulls number handler
type PatchReposOwnerRepoPullsNumberHandlerFunc func(PatchReposOwnerRepoPullsNumberParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchReposOwnerRepoPullsNumberHandlerFunc) Handle(params PatchReposOwnerRepoPullsNumberParams) middleware.Responder {
	return fn(params)
}

// PatchReposOwnerRepoPullsNumberHandler interface for that can handle valid patch repos owner repo pulls number params
type PatchReposOwnerRepoPullsNumberHandler interface {
	Handle(PatchReposOwnerRepoPullsNumberParams) middleware.Responder
}

// NewPatchReposOwnerRepoPullsNumber creates a new http.Handler for the patch repos owner repo pulls number operation
func NewPatchReposOwnerRepoPullsNumber(ctx *middleware.Context, handler PatchReposOwnerRepoPullsNumberHandler) *PatchReposOwnerRepoPullsNumber {
	return &PatchReposOwnerRepoPullsNumber{Context: ctx, Handler: handler}
}

/*PatchReposOwnerRepoPullsNumber swagger:route PATCH /repos/{owner}/{repo}/pulls/{number} patchReposOwnerRepoPullsNumber

Update a pull request.

*/
type PatchReposOwnerRepoPullsNumber struct {
	Context *middleware.Context
	Handler PatchReposOwnerRepoPullsNumberHandler
}

func (o *PatchReposOwnerRepoPullsNumber) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchReposOwnerRepoPullsNumberParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
