// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// PostReposOwnerRepoIssuesNumberLabelsCreatedCode is the HTTP code returned for type PostReposOwnerRepoIssuesNumberLabelsCreated
const PostReposOwnerRepoIssuesNumberLabelsCreatedCode int = 201

/*PostReposOwnerRepoIssuesNumberLabelsCreated Created

swagger:response postReposOwnerRepoIssuesNumberLabelsCreated
*/
type PostReposOwnerRepoIssuesNumberLabelsCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Label `json:"body,omitempty"`
}

// NewPostReposOwnerRepoIssuesNumberLabelsCreated creates PostReposOwnerRepoIssuesNumberLabelsCreated with default headers values
func NewPostReposOwnerRepoIssuesNumberLabelsCreated() *PostReposOwnerRepoIssuesNumberLabelsCreated {
	return &PostReposOwnerRepoIssuesNumberLabelsCreated{}
}

// WithPayload adds the payload to the post repos owner repo issues number labels created response
func (o *PostReposOwnerRepoIssuesNumberLabelsCreated) WithPayload(payload *models.Label) *PostReposOwnerRepoIssuesNumberLabelsCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post repos owner repo issues number labels created response
func (o *PostReposOwnerRepoIssuesNumberLabelsCreated) SetPayload(payload *models.Label) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostReposOwnerRepoIssuesNumberLabelsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostReposOwnerRepoIssuesNumberLabelsForbiddenCode is the HTTP code returned for type PostReposOwnerRepoIssuesNumberLabelsForbidden
const PostReposOwnerRepoIssuesNumberLabelsForbiddenCode int = 403

/*PostReposOwnerRepoIssuesNumberLabelsForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response postReposOwnerRepoIssuesNumberLabelsForbidden
*/
type PostReposOwnerRepoIssuesNumberLabelsForbidden struct {
}

// NewPostReposOwnerRepoIssuesNumberLabelsForbidden creates PostReposOwnerRepoIssuesNumberLabelsForbidden with default headers values
func NewPostReposOwnerRepoIssuesNumberLabelsForbidden() *PostReposOwnerRepoIssuesNumberLabelsForbidden {
	return &PostReposOwnerRepoIssuesNumberLabelsForbidden{}
}

// WriteResponse to the client
func (o *PostReposOwnerRepoIssuesNumberLabelsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
