// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// PostReposOwnerRepoLabelsCreatedCode is the HTTP code returned for type PostReposOwnerRepoLabelsCreated
const PostReposOwnerRepoLabelsCreatedCode int = 201

/*PostReposOwnerRepoLabelsCreated Created

swagger:response postReposOwnerRepoLabelsCreated
*/
type PostReposOwnerRepoLabelsCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Label `json:"body,omitempty"`
}

// NewPostReposOwnerRepoLabelsCreated creates PostReposOwnerRepoLabelsCreated with default headers values
func NewPostReposOwnerRepoLabelsCreated() *PostReposOwnerRepoLabelsCreated {
	return &PostReposOwnerRepoLabelsCreated{}
}

// WithPayload adds the payload to the post repos owner repo labels created response
func (o *PostReposOwnerRepoLabelsCreated) WithPayload(payload *models.Label) *PostReposOwnerRepoLabelsCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post repos owner repo labels created response
func (o *PostReposOwnerRepoLabelsCreated) SetPayload(payload *models.Label) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostReposOwnerRepoLabelsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostReposOwnerRepoLabelsForbiddenCode is the HTTP code returned for type PostReposOwnerRepoLabelsForbidden
const PostReposOwnerRepoLabelsForbiddenCode int = 403

/*PostReposOwnerRepoLabelsForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response postReposOwnerRepoLabelsForbidden
*/
type PostReposOwnerRepoLabelsForbidden struct {
}

// NewPostReposOwnerRepoLabelsForbidden creates PostReposOwnerRepoLabelsForbidden with default headers values
func NewPostReposOwnerRepoLabelsForbidden() *PostReposOwnerRepoLabelsForbidden {
	return &PostReposOwnerRepoLabelsForbidden{}
}

// WriteResponse to the client
func (o *PostReposOwnerRepoLabelsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
