// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostReposOwnerRepoKeysHandlerFunc turns a function with the right signature into a post repos owner repo keys handler
type PostReposOwnerRepoKeysHandlerFunc func(PostReposOwnerRepoKeysParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostReposOwnerRepoKeysHandlerFunc) Handle(params PostReposOwnerRepoKeysParams) middleware.Responder {
	return fn(params)
}

// PostReposOwnerRepoKeysHandler interface for that can handle valid post repos owner repo keys params
type PostReposOwnerRepoKeysHandler interface {
	Handle(PostReposOwnerRepoKeysParams) middleware.Responder
}

// NewPostReposOwnerRepoKeys creates a new http.Handler for the post repos owner repo keys operation
func NewPostReposOwnerRepoKeys(ctx *middleware.Context, handler PostReposOwnerRepoKeysHandler) *PostReposOwnerRepoKeys {
	return &PostReposOwnerRepoKeys{Context: ctx, Handler: handler}
}

/*PostReposOwnerRepoKeys swagger:route POST /repos/{owner}/{repo}/keys postReposOwnerRepoKeys

Create a key.

*/
type PostReposOwnerRepoKeys struct {
	Context *middleware.Context
	Handler PostReposOwnerRepoKeysHandler
}

func (o *PostReposOwnerRepoKeys) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostReposOwnerRepoKeysParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
