// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// PostReposOwnerRepoReleasesCreatedCode is the HTTP code returned for type PostReposOwnerRepoReleasesCreated
const PostReposOwnerRepoReleasesCreatedCode int = 201

/*PostReposOwnerRepoReleasesCreated Created

swagger:response postReposOwnerRepoReleasesCreated
*/
type PostReposOwnerRepoReleasesCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Release `json:"body,omitempty"`
}

// NewPostReposOwnerRepoReleasesCreated creates PostReposOwnerRepoReleasesCreated with default headers values
func NewPostReposOwnerRepoReleasesCreated() *PostReposOwnerRepoReleasesCreated {
	return &PostReposOwnerRepoReleasesCreated{}
}

// WithPayload adds the payload to the post repos owner repo releases created response
func (o *PostReposOwnerRepoReleasesCreated) WithPayload(payload *models.Release) *PostReposOwnerRepoReleasesCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post repos owner repo releases created response
func (o *PostReposOwnerRepoReleasesCreated) SetPayload(payload *models.Release) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostReposOwnerRepoReleasesCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostReposOwnerRepoReleasesForbiddenCode is the HTTP code returned for type PostReposOwnerRepoReleasesForbidden
const PostReposOwnerRepoReleasesForbiddenCode int = 403

/*PostReposOwnerRepoReleasesForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response postReposOwnerRepoReleasesForbidden
*/
type PostReposOwnerRepoReleasesForbidden struct {
}

// NewPostReposOwnerRepoReleasesForbidden creates PostReposOwnerRepoReleasesForbidden with default headers values
func NewPostReposOwnerRepoReleasesForbidden() *PostReposOwnerRepoReleasesForbidden {
	return &PostReposOwnerRepoReleasesForbidden{}
}

// WriteResponse to the client
func (o *PostReposOwnerRepoReleasesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
