// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/techzilla/gitapi/models"
)

// PostReposOwnerRepoGitCommitsCreatedCode is the HTTP code returned for type PostReposOwnerRepoGitCommitsCreated
const PostReposOwnerRepoGitCommitsCreatedCode int = 201

/*PostReposOwnerRepoGitCommitsCreated Created

swagger:response postReposOwnerRepoGitCommitsCreated
*/
type PostReposOwnerRepoGitCommitsCreated struct {

	/*
	  In: Body
	*/
	Payload *models.GitCommit `json:"body,omitempty"`
}

// NewPostReposOwnerRepoGitCommitsCreated creates PostReposOwnerRepoGitCommitsCreated with default headers values
func NewPostReposOwnerRepoGitCommitsCreated() *PostReposOwnerRepoGitCommitsCreated {
	return &PostReposOwnerRepoGitCommitsCreated{}
}

// WithPayload adds the payload to the post repos owner repo git commits created response
func (o *PostReposOwnerRepoGitCommitsCreated) WithPayload(payload *models.GitCommit) *PostReposOwnerRepoGitCommitsCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post repos owner repo git commits created response
func (o *PostReposOwnerRepoGitCommitsCreated) SetPayload(payload *models.GitCommit) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostReposOwnerRepoGitCommitsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostReposOwnerRepoGitCommitsForbiddenCode is the HTTP code returned for type PostReposOwnerRepoGitCommitsForbidden
const PostReposOwnerRepoGitCommitsForbiddenCode int = 403

/*PostReposOwnerRepoGitCommitsForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response postReposOwnerRepoGitCommitsForbidden
*/
type PostReposOwnerRepoGitCommitsForbidden struct {
}

// NewPostReposOwnerRepoGitCommitsForbidden creates PostReposOwnerRepoGitCommitsForbidden with default headers values
func NewPostReposOwnerRepoGitCommitsForbidden() *PostReposOwnerRepoGitCommitsForbidden {
	return &PostReposOwnerRepoGitCommitsForbidden{}
}

// WriteResponse to the client
func (o *PostReposOwnerRepoGitCommitsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
