// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutReposOwnerRepoContentsPathHandlerFunc turns a function with the right signature into a put repos owner repo contents path handler
type PutReposOwnerRepoContentsPathHandlerFunc func(PutReposOwnerRepoContentsPathParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutReposOwnerRepoContentsPathHandlerFunc) Handle(params PutReposOwnerRepoContentsPathParams) middleware.Responder {
	return fn(params)
}

// PutReposOwnerRepoContentsPathHandler interface for that can handle valid put repos owner repo contents path params
type PutReposOwnerRepoContentsPathHandler interface {
	Handle(PutReposOwnerRepoContentsPathParams) middleware.Responder
}

// NewPutReposOwnerRepoContentsPath creates a new http.Handler for the put repos owner repo contents path operation
func NewPutReposOwnerRepoContentsPath(ctx *middleware.Context, handler PutReposOwnerRepoContentsPathHandler) *PutReposOwnerRepoContentsPath {
	return &PutReposOwnerRepoContentsPath{Context: ctx, Handler: handler}
}

/*PutReposOwnerRepoContentsPath swagger:route PUT /repos/{owner}/{repo}/contents/{path} putReposOwnerRepoContentsPath

Create a file.

*/
type PutReposOwnerRepoContentsPath struct {
	Context *middleware.Context
	Handler PutReposOwnerRepoContentsPathHandler
}

func (o *PutReposOwnerRepoContentsPath) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutReposOwnerRepoContentsPathParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
