// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutUserStarredOwnerRepoNoContentCode is the HTTP code returned for type PutUserStarredOwnerRepoNoContent
const PutUserStarredOwnerRepoNoContentCode int = 204

/*PutUserStarredOwnerRepoNoContent Repository starred.

swagger:response putUserStarredOwnerRepoNoContent
*/
type PutUserStarredOwnerRepoNoContent struct {
}

// NewPutUserStarredOwnerRepoNoContent creates PutUserStarredOwnerRepoNoContent with default headers values
func NewPutUserStarredOwnerRepoNoContent() *PutUserStarredOwnerRepoNoContent {
	return &PutUserStarredOwnerRepoNoContent{}
}

// WriteResponse to the client
func (o *PutUserStarredOwnerRepoNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PutUserStarredOwnerRepoForbiddenCode is the HTTP code returned for type PutUserStarredOwnerRepoForbidden
const PutUserStarredOwnerRepoForbiddenCode int = 403

/*PutUserStarredOwnerRepoForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response putUserStarredOwnerRepoForbidden
*/
type PutUserStarredOwnerRepoForbidden struct {
}

// NewPutUserStarredOwnerRepoForbidden creates PutUserStarredOwnerRepoForbidden with default headers values
func NewPutUserStarredOwnerRepoForbidden() *PutUserStarredOwnerRepoForbidden {
	return &PutUserStarredOwnerRepoForbidden{}
}

// WriteResponse to the client
func (o *PutUserStarredOwnerRepoForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
