// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutGistsIDStarNoContentCode is the HTTP code returned for type PutGistsIDStarNoContent
const PutGistsIDStarNoContentCode int = 204

/*PutGistsIDStarNoContent Starred.

swagger:response putGistsIdStarNoContent
*/
type PutGistsIDStarNoContent struct {
}

// NewPutGistsIDStarNoContent creates PutGistsIDStarNoContent with default headers values
func NewPutGistsIDStarNoContent() *PutGistsIDStarNoContent {
	return &PutGistsIDStarNoContent{}
}

// WriteResponse to the client
func (o *PutGistsIDStarNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PutGistsIDStarForbiddenCode is the HTTP code returned for type PutGistsIDStarForbidden
const PutGistsIDStarForbiddenCode int = 403

/*PutGistsIDStarForbidden API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
for details.


swagger:response putGistsIdStarForbidden
*/
type PutGistsIDStarForbidden struct {
}

// NewPutGistsIDStarForbidden creates PutGistsIDStarForbidden with default headers values
func NewPutGistsIDStarForbidden() *PutGistsIDStarForbidden {
	return &PutGistsIDStarForbidden{}
}

// WriteResponse to the client
func (o *PutGistsIDStarForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
