// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi GitHub
Powerful collaboration, code review, and code management for open source and private projects.


Terms Of Service:

https://help.github.com/articles/github-terms-of-service/#b-api-terms


    Schemes:
      https
    Host: api.github.com
    BasePath: /
    Version: v3

    Consumes:
    - application/json
    - text/plain

    Produces:
    - application/json
    - text/html

swagger:meta
*/
package restapi
