// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ContributorsStatsItems contributors stats items
// swagger:model contributorsStatsItems
type ContributorsStatsItems struct {

	// author
	Author *ContributorsStatsItemsAuthor `json:"author,omitempty"`

	// The Total number of commits authored by the contributor.
	Total int64 `json:"total,omitempty"`

	// weeks
	Weeks ContributorsStatsItemsWeeks `json:"weeks"`
}

// Validate validates this contributors stats items
func (m *ContributorsStatsItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuthor(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContributorsStatsItems) validateAuthor(formats strfmt.Registry) error {

	if swag.IsZero(m.Author) { // not required
		return nil
	}

	if m.Author != nil {

		if err := m.Author.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("author")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ContributorsStatsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContributorsStatsItems) UnmarshalBinary(b []byte) error {
	var res ContributorsStatsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
