// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Feeds feeds
// swagger:model feeds
type Feeds struct {

	// links
	Links *FeedsLinks `json:"_links,omitempty"`

	// current user actor url
	CurrentUserActorURL string `json:"current_user_actor_url,omitempty"`

	// current user organization url
	CurrentUserOrganizationURL string `json:"current_user_organization_url,omitempty"`

	// current user public
	CurrentUserPublic string `json:"current_user_public,omitempty"`

	// current user url
	CurrentUserURL string `json:"current_user_url,omitempty"`

	// timeline url
	TimelineURL string `json:"timeline_url,omitempty"`

	// user url
	UserURL string `json:"user_url,omitempty"`
}

// Validate validates this feeds
func (m *Feeds) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Feeds) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.Links) { // not required
		return nil
	}

	if m.Links != nil {

		if err := m.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Feeds) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Feeds) UnmarshalBinary(b []byte) error {
	var res Feeds
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
