// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GistsItemsFiles gists items files
// swagger:model gistsItemsFiles
type GistsItemsFiles struct {

	// ring erl
	RingErl *GistsItemsFilesRingErl `json:"ring.erl,omitempty"`
}

// Validate validates this gists items files
func (m *GistsItemsFiles) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRingErl(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GistsItemsFiles) validateRingErl(formats strfmt.Registry) error {

	if swag.IsZero(m.RingErl) { // not required
		return nil
	}

	if m.RingErl != nil {

		if err := m.RingErl.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ring.erl")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GistsItemsFiles) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GistsItemsFiles) UnmarshalBinary(b []byte) error {
	var res GistsItemsFiles
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
