// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// MergesBody merges body
// swagger:model mergesBody
type MergesBody struct {

	// base
	Base string `json:"base,omitempty"`

	// commit message
	CommitMessage string `json:"commit_message,omitempty"`

	// head
	Head string `json:"head,omitempty"`
}

// Validate validates this merges body
func (m *MergesBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *MergesBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MergesBody) UnmarshalBinary(b []byte) error {
	var res MergesBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
