// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PatchGistFilesNewFileTxt patch gist files new file txt
// swagger:model patchGistFilesNewFileTxt
type PatchGistFilesNewFileTxt struct {

	// content
	Content string `json:"content,omitempty"`
}

// Validate validates this patch gist files new file txt
func (m *PatchGistFilesNewFileTxt) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PatchGistFilesNewFileTxt) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchGistFilesNewFileTxt) UnmarshalBinary(b []byte) error {
	var res PatchGistFilesNewFileTxt
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
