// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PostGistFilesFile1Txt post gist files file1 txt
// swagger:model postGistFilesFile1Txt
type PostGistFilesFile1Txt struct {

	// content
	Content string `json:"content,omitempty"`
}

// Validate validates this post gist files file1 txt
func (m *PostGistFilesFile1Txt) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PostGistFilesFile1Txt) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostGistFilesFile1Txt) UnmarshalBinary(b []byte) error {
	var res PostGistFilesFile1Txt
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
