// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PullRequest pull request
// swagger:model pullRequest
type PullRequest struct {

	// links
	Links *PullRequestLinks `json:"_links,omitempty"`

	// additions
	Additions int64 `json:"additions,omitempty"`

	// base
	Base *PullRequestBase `json:"base,omitempty"`

	// body
	Body string `json:"body,omitempty"`

	// changed files
	ChangedFiles int64 `json:"changed_files,omitempty"`

	// closed at
	ClosedAt string `json:"closed_at,omitempty"`

	// comments
	Comments int64 `json:"comments,omitempty"`

	// commits
	Commits int64 `json:"commits,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// deletions
	Deletions int64 `json:"deletions,omitempty"`

	// diff url
	DiffURL string `json:"diff_url,omitempty"`

	// head
	Head *PullRequestHead `json:"head,omitempty"`

	// html url
	HTMLURL string `json:"html_url,omitempty"`

	// issue url
	IssueURL string `json:"issue_url,omitempty"`

	// merge commit sha
	MergeCommitSha string `json:"merge_commit_sha,omitempty"`

	// mergeable
	Mergeable bool `json:"mergeable,omitempty"`

	// merged
	Merged bool `json:"merged,omitempty"`

	// merged at
	MergedAt string `json:"merged_at,omitempty"`

	// merged by
	MergedBy *PullRequestMergedBy `json:"merged_by,omitempty"`

	// number
	Number int64 `json:"number,omitempty"`

	// patch url
	PatchURL string `json:"patch_url,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`

	// url
	URL string `json:"url,omitempty"`

	// user
	User *PullRequestUser `json:"user,omitempty"`
}

// Validate validates this pull request
func (m *PullRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateBase(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateHead(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateMergedBy(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateUser(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PullRequest) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.Links) { // not required
		return nil
	}

	if m.Links != nil {

		if err := m.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links")
			}
			return err
		}
	}

	return nil
}

func (m *PullRequest) validateBase(formats strfmt.Registry) error {

	if swag.IsZero(m.Base) { // not required
		return nil
	}

	if m.Base != nil {

		if err := m.Base.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("base")
			}
			return err
		}
	}

	return nil
}

func (m *PullRequest) validateHead(formats strfmt.Registry) error {

	if swag.IsZero(m.Head) { // not required
		return nil
	}

	if m.Head != nil {

		if err := m.Head.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("head")
			}
			return err
		}
	}

	return nil
}

func (m *PullRequest) validateMergedBy(formats strfmt.Registry) error {

	if swag.IsZero(m.MergedBy) { // not required
		return nil
	}

	if m.MergedBy != nil {

		if err := m.MergedBy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("merged_by")
			}
			return err
		}
	}

	return nil
}

func (m *PullRequest) validateUser(formats strfmt.Registry) error {

	if swag.IsZero(m.User) { // not required
		return nil
	}

	if m.User != nil {

		if err := m.User.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("user")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PullRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PullRequest) UnmarshalBinary(b []byte) error {
	var res PullRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
