// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PullsItems pulls items
// swagger:model pullsItems
type PullsItems struct {

	// links
	Links *PullsItemsLinks `json:"_links,omitempty"`

	// base
	Base *PullsItemsBase `json:"base,omitempty"`

	// body
	Body string `json:"body,omitempty"`

	// ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ
	ClosedAt string `json:"closed_at,omitempty"`

	// ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ
	CreatedAt string `json:"created_at,omitempty"`

	// diff url
	DiffURL string `json:"diff_url,omitempty"`

	// head
	Head *PullsItemsHead `json:"head,omitempty"`

	// html url
	HTMLURL string `json:"html_url,omitempty"`

	// issue url
	IssueURL string `json:"issue_url,omitempty"`

	// ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ
	MergedAt string `json:"merged_at,omitempty"`

	// number
	Number int64 `json:"number,omitempty"`

	// patch url
	PatchURL string `json:"patch_url,omitempty"`

	// state
	State interface{} `json:"state,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ
	UpdatedAt string `json:"updated_at,omitempty"`

	// url
	URL string `json:"url,omitempty"`

	// user
	User *PullsItemsUser `json:"user,omitempty"`
}

// Validate validates this pulls items
func (m *PullsItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLinks(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateBase(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateHead(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateUser(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PullsItems) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.Links) { // not required
		return nil
	}

	if m.Links != nil {

		if err := m.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links")
			}
			return err
		}
	}

	return nil
}

func (m *PullsItems) validateBase(formats strfmt.Registry) error {

	if swag.IsZero(m.Base) { // not required
		return nil
	}

	if m.Base != nil {

		if err := m.Base.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("base")
			}
			return err
		}
	}

	return nil
}

func (m *PullsItems) validateHead(formats strfmt.Registry) error {

	if swag.IsZero(m.Head) { // not required
		return nil
	}

	if m.Head != nil {

		if err := m.Head.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("head")
			}
			return err
		}
	}

	return nil
}

var pullsItemsTypeStatePropEnum []interface{}

func init() {
	var res []interface{}
	if err := json.Unmarshal([]byte(`["open","closed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		pullsItemsTypeStatePropEnum = append(pullsItemsTypeStatePropEnum, v)
	}
}

// prop value enum
func (m *PullsItems) validateStateEnum(path, location string, value interface{}) error {
	if err := validate.Enum(path, location, value, pullsItemsTypeStatePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *PullsItems) validateState(formats strfmt.Registry) error {

	if swag.IsZero(m.State) { // not required
		return nil
	}

	return nil
}

func (m *PullsItems) validateUser(formats strfmt.Registry) error {

	if swag.IsZero(m.User) { // not required
		return nil
	}

	if m.User != nil {

		if err := m.User.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("user")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PullsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PullsItems) UnmarshalBinary(b []byte) error {
	var res PullsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
