// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PullsItemsLinksComments pulls items links comments
// swagger:model pullsItemsLinksComments
type PullsItemsLinksComments struct {

	// href
	Href string `json:"href,omitempty"`
}

// Validate validates this pulls items links comments
func (m *PullsItemsLinksComments) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PullsItemsLinksComments) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PullsItemsLinksComments) UnmarshalBinary(b []byte) error {
	var res PullsItemsLinksComments
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
