// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SearchIssuesItemsItems search issues items items
// swagger:model searchIssuesItemsItems
type SearchIssuesItemsItems struct {

	// assignee
	Assignee SearchIssuesItemsItemsAssignee `json:"assignee,omitempty"`

	// body
	Body string `json:"body,omitempty"`

	// closed at
	ClosedAt SearchIssuesItemsItemsClosedAt `json:"closed_at,omitempty"`

	// comments
	Comments int64 `json:"comments,omitempty"`

	// comments url
	CommentsURL string `json:"comments_url,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// events url
	EventsURL string `json:"events_url,omitempty"`

	// html url
	HTMLURL string `json:"html_url,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// labels
	Labels SearchIssuesItemsItemsLabels `json:"labels"`

	// labels url
	LabelsURL string `json:"labels_url,omitempty"`

	// milestone
	Milestone SearchIssuesItemsItemsMilestone `json:"milestone,omitempty"`

	// number
	Number int64 `json:"number,omitempty"`

	// pull request
	PullRequest *SearchIssuesItemsItemsPullRequest `json:"pull_request,omitempty"`

	// score
	Score float64 `json:"score,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`

	// url
	URL string `json:"url,omitempty"`

	// user
	User *SearchIssuesItemsItemsUser `json:"user,omitempty"`
}

// Validate validates this search issues items items
func (m *SearchIssuesItemsItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePullRequest(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateUser(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SearchIssuesItemsItems) validatePullRequest(formats strfmt.Registry) error {

	if swag.IsZero(m.PullRequest) { // not required
		return nil
	}

	if m.PullRequest != nil {

		if err := m.PullRequest.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pull_request")
			}
			return err
		}
	}

	return nil
}

func (m *SearchIssuesItemsItems) validateUser(formats strfmt.Registry) error {

	if swag.IsZero(m.User) { // not required
		return nil
	}

	if m.User != nil {

		if err := m.User.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("user")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SearchIssuesItemsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SearchIssuesItemsItems) UnmarshalBinary(b []byte) error {
	var res SearchIssuesItemsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
