// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SearchRepositoriesByKeywordRepositoriesItems search repositories by keyword repositories items
// swagger:model searchRepositoriesByKeywordRepositoriesItems
type SearchRepositoriesByKeywordRepositoriesItems struct {

	// created
	Created string `json:"created,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// followers
	Followers int64 `json:"followers,omitempty"`

	// fork
	Fork bool `json:"fork,omitempty"`

	// forks
	Forks int64 `json:"forks,omitempty"`

	// has downloads
	HasDownloads bool `json:"has_downloads,omitempty"`

	// has issues
	HasIssues bool `json:"has_issues,omitempty"`

	// has wiki
	HasWiki bool `json:"has_wiki,omitempty"`

	// homepage
	Homepage string `json:"homepage,omitempty"`

	// language
	Language string `json:"language,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// open issues
	OpenIssues int64 `json:"open_issues,omitempty"`

	// owner
	Owner string `json:"owner,omitempty"`

	// private
	Private bool `json:"private,omitempty"`

	// pushed
	Pushed string `json:"pushed,omitempty"`

	// pushed at
	PushedAt string `json:"pushed_at,omitempty"`

	// score
	Score float64 `json:"score,omitempty"`

	// size
	Size int64 `json:"size,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// url
	URL string `json:"url,omitempty"`

	// username
	Username string `json:"username,omitempty"`

	// watchers
	Watchers int64 `json:"watchers,omitempty"`
}

// Validate validates this search repositories by keyword repositories items
func (m *SearchRepositoriesByKeywordRepositoriesItems) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SearchRepositoriesByKeywordRepositoriesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SearchRepositoriesByKeywordRepositoriesItems) UnmarshalBinary(b []byte) error {
	var res SearchRepositoriesByKeywordRepositoriesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
