// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SearchIssuesByKeywordIssuesItems search issues by keyword issues items
// swagger:model searchIssuesByKeywordIssuesItems
type SearchIssuesByKeywordIssuesItems struct {

	// body
	Body string `json:"body,omitempty"`

	// comments
	Comments int64 `json:"comments,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// gravatar id
	GravatarID string `json:"gravatar_id,omitempty"`

	// html url
	HTMLURL string `json:"html_url,omitempty"`

	// labels
	Labels []string `json:"labels"`

	// number
	Number int64 `json:"number,omitempty"`

	// position
	Position int64 `json:"position,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`

	// user
	User string `json:"user,omitempty"`

	// votes
	Votes int64 `json:"votes,omitempty"`
}

// Validate validates this search issues by keyword issues items
func (m *SearchIssuesByKeywordIssuesItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLabels(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SearchIssuesByKeywordIssuesItems) validateLabels(formats strfmt.Registry) error {

	if swag.IsZero(m.Labels) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SearchIssuesByKeywordIssuesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SearchIssuesByKeywordIssuesItems) UnmarshalBinary(b []byte) error {
	var res SearchIssuesByKeywordIssuesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
